Translating tutorial/modules.
python-docs-tr/python-docs-tr pull request #12
Opened 2022-01-05 17:28 UTC by jrambrosia

2022-01-05 17:46 UTC, Ardasak approved these changes
Eridim desem yeridir...

2022-01-05 18:05 UTC, Ardasak commented
@egeakman ayıp oluyor.

2022-01-25 19:56 UTC, Ardasak requested changes
helal kardesim adamsinnn

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +"kullanışlı bir fonksiyonu kullanmak isteyebilirsiniz."
```suggestion
"Python yorumlayıcısından çıkıp tekrar girerseniz, yaptığınız tanımlar "
"(fonksiyonlar  ve değişkenler) kaybolur. Bu nedenle, daha uzun bir "
"program yazmak istiyorsanız, girdiyi yorumlayıcıya hazırlarken bir metin "
"düzenleyicisi kullanmak ve o dosyayla girdi olarak çalıştırmak "
"daha iyidir.  Bu bir *script* oluşturma olarak bilinir.  Programınız "
"uzadıkça, daha kolay bakım için birkaç dosyaya bölmek isteyebilirsiniz.  "
"Ayrıca, tanımını her programa kopyalamadan, birkaç programda yazdığınız "
"kullanışlı bir fonksiyonu kullanmak isteyebilirsiniz."
```

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +"değişkenlerin derlenmesi) aktarılabilir."
```suggestion
"Bunu desteklemek için Python, tanımları bir dosyaya koymanın ve bunları bir "
"komut dosyasında veya yorumlayıcının etkileşimli bir örneğinde kullanmanın "
"bir yolunu sağlar. Böyle bir dosyaya *module* denir; bir modülden alınan "
"tanımlar diğer modüllere veya *main* modülüne (en üst düzeyde ve hesap "
"makinesi modunda yürütülen bir komut dosyasında erişiminiz olan "
"değişkenlerin derlenmesi) aktarılabilir."
```

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +"dosya oluşturmak için en sevdiğiniz metin düzenleyicisini kullanın::"
```suggestion
"Modül, Python tanımlarını ve ifadelerini içeren bir dosyadır.  Dosya adı, :"
"file:`.py` son ekini içeren modül adıdır.  Bir modül içinde, modülün adı "
"(dize olarak) ``__name__`` genel değişkeninin değeri olarak kullanılabilir.  "
"Örneğin, geçerli dizinde aşağıdaki içeriklerle :file:`fibo.py` adlı bir "
"dosya oluşturmak için en sevdiğiniz metin düzenleyicisini kullanın::"
```

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +"kullanarak şu işlevlere erişebilirsiniz::"
```suggestion
"Bu, ``fibo`` içinde tanımlanan işlevlerin adlarını doğrudan geçerli sembol "
"tablosuna girmez; sadece ``fibo`` modül adını oraya girer. Modül adını "
"kullanarak şu işlevlere erişebilirsiniz::"
```

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +msgstr "Modüller hakkında daha fazla şey"
```suggestion
msgstr "Modüller hakkında daha fazla"
```

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +"modülünün genel sembol tablosuna yerleştirilir."
```suggestion
"Modüller diğer modülleri içe aktarabilir.  Alışılmıştır, ancak tüm :"
"keyword:`import` ifadelerini bir modülün (veya komut dosyasının) başına "
"yerleştirmek gerekli değildir.  İçe aktarılan modül adları, içe aktarma "
"modülünün genel sembol tablosuna yerleştirilir."
```

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +"komut dosyası olarak yürütülürse de çalıştırılırlar.)"
```suggestion
"Bir modül, işlev tanımlarının yanı sıra çalıştırılabilir ifadeler de "
"içerebilir. Bu ifadeler modülü başlatmayı amaçlamaktadır. Yalnızca bir "
"import ifadesinde modül adıyla karşılaşıldığında *ilk* kez yürütülürler. [#]_ (Dosya "
"komut dosyası olarak yürütülürse de çalıştırılırlar.)"
```

2022-01-25 19:56 UTC, Ardasak commented on tutorial/modules.po
> +"dokunabilirsiniz."
```suggestion
"Her modülün, modülde tanımlanan tüm fonksiyonlar tarafından genel sembol "
"tablosu olarak kullanılan kendi özel sembol tablosu vardır. Böylece, bir "
"modülün yazarı, kullanıcının genel değişkenleriyle yanlışlıkla çakışmalar "
"konusunda endişelenmeden modüldeki genel değişkenleri kullanabilir. Öte "
"yandan, ne yaptığınızı biliyorsanız, bir modülün genel değişkenlerine, "
"``modname.itemname`` işlevlerini ifade etmek için kullanılan aynı notasyonla "
"iletişime geçebilirsiniz."
```

2022-02-04 20:49 UTC, sefikaozturk approved these changes

2022-03-02 18:40 UTC, Ardasak commented on tutorial/modules.po
> +"başlatılır. Standart liste işlemlerini kullanarak değiştirebilirsiniz::"
```suggestion
"``sys.path`` değişkeni, yorumlayıcının modüller için arama yolunu belirleyen bir "
"dizeler listesidir. :envvar:`PYTHONPATH` ortam değişkeninden veya :envvar:"
"`PYTHONPATH` ayarlanmamışsa yerleşik bir varsayılan değerden alınan varsayılan bir yola "
"başlatılır. Standart liste işlemlerini kullanarak değiştirebilirsiniz::"
```

2022-03-02 19:04 UTC, Ardasak commented on tutorial/modules.po
> +"istemleri olarak kullanılan dizeleri tanımlar:"
```suggestion
"Python, ayrı bir belge olan Python Kütüphanesi Referansında (bundan sonra \"Kütüphane "
"Referansı\") açıklanan standart modüllerden oluşan bir kütüphane ile birlikte gelir. "
"Bazı modüller yorumlayıcıya yerleştirilmiştir; bunlar, dilin çekirdeğinin bir "
"parçası olmayan, ancak yine de verimlilik için veya sistem çağrıları gibi işletim "
"sistemi ilkellerine erişim sağlamak için yerleşik olan işlemlere erişim sağlar. Bu "
"tür modüller seti, aynı zamanda temel platforma da bağlı olan bir yapılandırma "
"seçeneğidir. Örneğin, :mod:`winreg` modülü yalnızca Windows sistemlerinde sağlanır. "
"Belirli bir modül biraz ilgiyi hak ediyor: Her Python yorumlayıcısında yerleşik "
"olan :mod:`sys`. ``sys.ps1`` ve ``sys.ps2`` değişkenleri, birincil ve ikincil bilgi "
"istemleri olarak kullanılan dizeleri tanımlar:"
```

2022-03-02 19:12 UTC, Ardasak commented on tutorial/modules.po
> +msgstr "Argümanlar olmadan, :func:`dir`, şu anda tanımladığınız adları listeler::"
```suggestion
msgstr "Parametreler olmadan, :func:`dir`, şu anda tanımladığınız adları listeler::"
```

2022-03-02 19:12 UTC, Ardasak commented on tutorial/modules.po
> +msgstr "Her tür adı listelediğini unutmayın: değişkenler, modüller, fonksiyonlar vb."
```suggestion
msgstr "Her tür adın listelendiğini unutmayın: değişkenler, modüller, fonksiyonlar vb."
```

2022-03-02 19:37 UTC, Ardasak commented on tutorial/modules.po
> +"bir listesini istiyorsanız, standart modülde tanımlanırlar :mod:`builtins`::"
```suggestion
":func:`dir` yerleşik fonksiyonlarun ve değişkenlerin adlarını listelemez. Bunların "
"bir listesini istiyorsanız, standart modül :mod:`builtins` 'de tanımlanırlar::"
```

2022-03-02 19:45 UTC, Ardasak commented on tutorial/modules.po
> +"cinsinden ifade edilir):"
```suggestion
"Ses dosyalarının ve ses verilerinin tek tip işlenmesi için bir modül koleksiyonu "
"(\"paket\") tasarlamak istediğinizi varsayalım. Birçok farklı ses dosyası biçimi "
"vardır (genellikle uzantılarıyla tanınır, örneğin: :file:`.wav`, :file:`.aiff`, :"
"file:`.au`) bu nedenle, çeşitli dosya biçimleri arasında dönüşüm için büyüyen bir "
"modül koleksiyonu oluşturmanız ve sürdürmeniz gerekebilir. Ses verileri üzerinde "
"gerçekleştirmek isteyebileceğiniz birçok farklı işlem de vardır (karıştırma, eko "
"ekleme, ekolayzır işlevi uygulama, yapay bir stereo efekti oluşturma gibi) bu "
"nedenle ek olarak, bu işlemleri gerçekleştirmek için hiç bitmeyen bir modül akışı "
"yazıyor olacaksınız. İşte paketiniz için olası bir yapı (hiyerarşik bir dosya sistemi "
"cinsinden ifade edilir):"
```

2022-03-02 19:48 UTC, Ardasak commented on tutorial/modules.po
> +"``__all__`` değişkenini ayarlayabilir."
```suggestion
"Python'un dosyayı içeren dizinleri paketler olarak ele alması için :file:`__init__."
"py` dosyaları gereklidir. Bu, ``string`` gibi ortak bir ada sahip dizinlerin, daha "
"sonra modül arama yolunda oluşan geçerli modülleri istemeden gizlemesini önler. En "
"basit durumda, :file:`__init__.py` yalnızca boş bir dosya olabilir, ancak aynı "
"zamanda paket için başlatma kodunu çalıştırabilir veya daha sonra açıklanacak olan "
"``__all__`` değişkenini ayarlayabilir."
```

2022-03-02 19:50 UTC, Ardasak commented on tutorial/modules.po
> +msgstr "Paketin kullanıcıları, paketten ayrı modülleri içe aktarabilir, örneğin::"
```suggestion
msgstr "Paketin kullanıcıları, paketin içindeki ayrı modülleri içe aktarabilir, örneğin::"
```

2022-03-02 20:23 UTC, Ardasak commented on tutorial/modules.po
> +"`sound.effects' paketinin içe aktarılmasını sağlar (muhtemelen herhangi bir başlatma "
```suggestion
"`sound.effects' paketinin içe aktarılmasını sağlar (mümkünse herhangi bir başlatma "
```

2022-03-02 20:24 UTC, Ardasak commented on tutorial/modules.po
> +"tanımlanmışlardır.(Bu aynı zamanda ``__all__`` tanımlandığında da çalışır.)"
```suggestion
"Bu örnekte, :mod:`echo` ve :mod:`surround` modülleri geçerli ad alanına aktarılır, "
"çünkü bunlar ``from...import`` ifadesi yürütüldüğünde :mod:`sound.effects` paketinde "
"tanımlanmışlardır. (Bu aynı zamanda ``__all__`` tanımlandığında da çalışır.)"
```

2022-03-02 20:28 UTC, Ardasak commented on tutorial/modules.po
> +"kullanması gerekmedikçe, önerilen gösterim budur."
```suggestion
"Unutmayın, `` from package import specific_submodule`` kullanmanın yanlış bir tarafı "
"yok! Aslında, içe aktarma modülünün farklı paketlerden aynı ada sahip alt modülleri "
"kullanması gerekmedikçe, önerilen gösterim budur."
```

2022-03-02 20:30 UTC, Ardasak commented on tutorial/modules.po
> +"genişletmek için kullanılabilir."
```suggestion
"Bu özelliğe sıklıkla ihtiyaç duyulmasa da, bir pakette bulunan modül dizisini "
"genişletmek için kullanılabilir."
```

2022-03-02 20:33 UTC, Ardasak commented on tutorial/modules.po
> +"effects import echo'yu kullanabilir. ``."
```suggestion
"Paketler alt paketler halinde yapılandırıldığında (örnekteki :mod:`sound` paketinde "
"olduğu gibi), kardeş paketlerin alt modüllerine atıfta bulunmak için mutlak içe "
"aktarma kullanabilirsiniz. Örneğin, :mod:`sound.filters.vocoder` modülünün :mod:"
"`sound.effects` paketindeki :mod:`echo` modülünü kullanması gerekiyorsa, ``from sound."
"effects import echo`` 'yu kullanabilir. ``."
```

2022-03-02 20:33 UTC, Ardasak commented on tutorial/modules.po
> +"`surround` modülünden şunları kullanabilirsiniz::"
```suggestion
"Ayrıca, içe aktarma ifadesinin ``from module import name`` formuyla göreli içe "
"aktarmaları da yazabilirsiniz. Bu içe aktarmalar, göreli içe aktarmada yer alan "
"mevcut ve ana paketleri belirtmek için baştaki noktaları kullanır. Örneğin :mod:"
"`surround` modülünden şunları kullanabilirsiniz::"
```

2022-06-05 18:27 UTC, irfan-karabacak approved these changes

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"nedenle örnekte ''fibo'' tanımlanmamıştır)."
```suggestion
"Bu, yerel sembol tablosunda içe aktarmaların alındığı modül adını tanıtmaz (bu "
"nedenle örnekte ``fibo`` tanımlanmamıştır)."
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"kümesi ekler ve muhtemelen önceden tanımladığınız bazı şeyleri gizler."
```suggestion
"Bu, alt çizgiyle başlayanlar (``_``) dışındaki tüm isimleri alır. Çoğu durumda "
"Python programcıları bu özelliği kullanmaz, çünkü yorumlayıcıya bilinmeyen bir ad "
"kümesi ekler ve muhtemelen önceden tanımladığınız bazı şeyleri gizler."
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"etkileşimli oturumlarda yazmayı kaydetmek için kullanmak sorun değildir."
```suggestion
"Genel olarak, bir modülden veya paketten ``*`` içeri aktarma uygulamasının, "
"genellikle okunamayan koda neden olduğundan hoş karşılanmadığına dikkat edin. Ancak, "
"etkileşimli oturumlarda yazmayı kaydetmek için kullanmak sorun değildir."
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"aktarılmasıdır, tek farkı \"fib\" olarak mevcut olmasıdır."
```suggestion
"Bu, modülün ``import fibo`` 'nun yapacağı şekilde etkin bir şekilde içe "
"aktarılmasıdır, tek farkı \``fib\`` olarak mevcut olmasıdır."
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +msgstr "Benzer efektlere sahip :keyword:'from' kullanılırken de kullanılabilir::"
```suggestion
msgstr "Benzer efektlere sahip :keyword:`from` kullanılırken de kullanılabilir::"
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"modülse, :func:'importlib.reload', örneğin ''importlib; importlib.reload(modüladı)''."
```suggestion
"Verimlilik nedeniyle, her modül yorumlayıcı oturumu başına yalnızca bir kez içe "
"aktarılır.  Bu nedenle, modüllerinizi değiştirirseniz, yorumlayıcıyı yeniden "
"başlatmanız gerekir - veya etkileşimli olarak test etmek istediğiniz tek bir "
"modülse, :func:`importlib.reload`, örneğin ``importlib; importlib.reload(modulename)``."
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"keyword:'import' deyiminin bir varyantı vardır.  Mesela::"
```suggestion
"Bir modülden adları doğrudan içe aktarma modülünün sembol tablosuna içe alan :"
"keyword:`import` deyiminin bir varyantı vardır.  Mesela::"
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"kümesi ekler ve muhtemelen önceden tanımladığınız bazı şeyleri gizler."
```suggestion
"Bu, alt çizgiyle başlayanlar (``_``) dışındaki tüm isimleri alır. Çoğu durumda "
"Python programcıları bu özelliği kullanmaz, çünkü yorumlayıcıya bilinmeyen bir ad "
"kümesi ekler ve muhtemelen önceden tanımladığınız bazı şeyleri gizler."
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"olarak yürütülürse çalışır:"
```suggestion
"dosyayı bir komut dosyası ve içe aktarılabilir bir modül olarak kullanılabilir hale "
"getirebilirsiniz, çünkü komut satırını ayrıştıran kod yalnızca modül \"main\" dosya "
"olarak yürütülürse çalışır:"
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"konumlardan başlatılır:"
```suggestion
":mod:`spam` adlı bir modül içe aktarıldığında, yorumlayıcı önce bu ada sahip "
"yerleşik bir modül arar. Bulunamazsa, `ata:`sys.path:d değişkeni tarafından verilen "
"dizinlerin listesinde :file:`spam.py` adlı bir dosyayı arar.  :d ata:`sys.path` şu "
"konumlardan başlatılır:"
```

2022-06-05 18:27 UTC, irfan-karabacak commented on tutorial/modules.po
> +"standardmodules' bölümüne bakın."
```suggestion
"Başlatıldıktan sonra Python programları :data:'sys.path' değiştirebilir.  "
"Çalıştırılmakta olan komut dosyasını içeren dizin, arama yolunun başına, standart "
"kitaplık yolunun önüne yerleştirilir. Bu, kitaplık dizininde aynı ada sahip modüller "
"yerine bu dizindeki komut dosyalarının yüklanacağı anlamına gelir. Değiştirme "
"amaçlanmadığı sürece bu bir hatadır.  Daha fazla bilgi için :ref:`tut-"
"standardmodules` bölümüne bakın."
```

2022-06-05 18:28 UTC, irfan-karabacak submitted a review, later dismissed
sak yapmis

2022-06-07 07:17 UTC, merged