Translated all.
python-docs-tr/python-docs-tr pull request #14
Opened 2022-01-06 19:23 UTC by KeroNar

2022-01-06 19:48 UTC, egeakman requested changes

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"Language-Team: Turkish Team\n"
```suggestion
"Language-Team: TURKISH <python.docs.tr@gmail.com>\n"
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +msgstr "Şimdi ne olacak?"
```suggestion
msgstr "Sırada Ne Var?"
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"--- python'u gerçek dünyadaki sorunlarınızı çözmeye uygulamaya istekli "
```suggestion
"--- Python'u gerçek dünyadaki sorunlarınızı çözmek için kullanmaya istekli "
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"Bu öğretici Python'un belge kümesinin bir parçasıdır.   Kümedeki diğer bazı "
```suggestion
"Bu öğretici Python'un dokümantasyon kümesinin bir parçasıdır.   Kümedeki diğer bazı "
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"size neler olduğu hakkında bir fikir verecektir."
```suggestion
"Türler, fonksiyonlar ve standart kütüphanedeki modüller hakkında eksiksiz (kısa "
"da olsa) referans materyali veren bu kılavuza göz atmalısınız.  Standart "
"Python dağıtımı birçok ek kod içerir. Unix posta kutularını okumak, HTTP "
"üzerinden belge almak, rastgele sayılar oluşturmak, komut satırı "
"seçeneklerini ayrıştırmak, CGI programları yazmak, verileri sıkıştırmak ve "
"diğer birçok görev için modüller vardır. Kütüphane Referansına göz atmak "
"size neler olduğu hakkında bir fikir verecektir."
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"çeşitli yerlerinde kopyalanır; bir kopya, coğrafi konumunuza bağlı olarak "
```suggestion
"bulundurur.  Bu web sitesi Avrupa, Japonya ve Avustralya gibi dünyanın "
"çeşitli yerlerinde kopyalanır; bir mirror, coğrafi konumunuza bağlı olarak "
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"bulabilmesi için buraya kaydedebilirsiniz."
```suggestion
"https://pypi.org: Daha önce Cheese Shop [#]_, olarak da adlandırılan Python "
"Paket Dizini, kullanıcılar tarafından oluşturulan ve indirilebilen Python "
"modülleri dizinidir.  Kodu yayınlamaya başladıktan sonra, başkalarının "
"bulabilmesi için buraya kaydedebilirsiniz."
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"(O'Reilly & Associates, ISBN 0-596-00797-3) adlı bir kitapta toplanır."
```suggestion
"https://code.activestate.com/recipes/langs/python/: Python Yemek Tarifleri; "
"kod örnekleri, daha geniş çaplı modüller ve kullanışlı kodların büyük "
"bir koleksiyonudur. Özellikle dikkat çekici katkılar Python Cookbook "
"(O'Reilly & Associates, ISBN 0-596-00797-3) adlı bir kitapta toplanır."
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"Posta listesi arşivleri için https://mail.python.org/pipermail/."
```suggestion
"Python ile ilgili sorular ve sorun raporları için haber grubu "
":newsgroup:`comp.lang.python` adresine gönderebilir veya bunları "
"python-list@python.org posta listesine gönderebilirsiniz.  Haber grubu ve posta "
"listesi aynı ağ içinde olduğundan, birine gönderilen iletiler otomatik "
"olarak diğerine iletilir.  Günde yüzlerce gönderi geliyor, sorular soruluyor "
"(ve yanıtlanıyor), yeni özellikler öneriliyor ve yeni modüller duyuruluyor. "
"Posta listesi arşivleri için https://mail.python.org/pipermail/."
```

2022-01-06 19:48 UTC, egeakman commented on tutorial/whatnow.po
> +"soruların çoğunu yanıtlar ve sorununuz için çözümü zaten içerebilir."
```suggestion
"Göndermeden önce, :ref:`Sık Sorulan Sorular <faq-index>`  (SSS olarak da "
"adlandırılır) listesini kontrol etmeyi unutmayın.  SSS, tekrar tekrar gelen "
"soruların çoğunu yanıtlar ve sorununuz için çözümü içerebilir."
```

2022-01-06 20:09 UTC, egeakman submitted a review, later dismissed

2022-01-07 15:56 UTC, sefikaozturk commented on tutorial/whatnow.po
> +"https://www.python.org: Ana Python web sitesi.  Site kod, bazı belgeler ve "
"https://www.python.org: Ana Python web sitesidir. Bu site; kod, bazı belgeler ve "

2022-01-07 15:58 UTC, sefikaozturk commented on tutorial/whatnow.po
> +"internet üzerindeki diğer Python'la alakalı sitelere yönlendirmeler "
"Python ile ilgili diğer internet sitelerine yönlendirmeler "

2022-01-07 15:59 UTC, sefikaozturk commented on tutorial/whatnow.po
> +"Paket Dizini, kullanıcılar tarafından oluşturulan ve indirilebilen Python "
"Paket Dizini, kullanıcılar tarafından oluşturulan indirilebilir Python "

2022-01-07 16:01 UTC, sefikaozturk commented on tutorial/whatnow.po
> +"soruların çoğunu yanıtlar ve sorununuz için çözümü içerebilir."
"soruların çoğunu yanıtlar ve halihazırda sorununuzun çözümünü içeriyor olabilir."

2022-01-07 16:02 UTC, sefikaozturk commented on tutorial/whatnow.po
> +"\"Cheese Shop\" bir Monty Python'un çizimidir: bir müşteri peynir dükkanına "
"\"Cheese Shop\" Monty Python'un bir çizimidir: bir müşteri peynir dükkanına "

2022-01-07 16:39 UTC, Ardasak requested changes
Güzel olmuş, bu kısımları düzenleyebiliriz. Adamsın.

2022-01-07 16:39 UTC, Ardasak commented on tutorial/whatnow.po
> +"https://www.python.org: Ana Python web sitesi.  Site kod, bazı belgeler ve "
```suggestion
"https://www.python.org: Ana Python web sitesidir. Bu site; kod, bazı belgeler ve "
```

2022-01-07 16:39 UTC, Ardasak commented on tutorial/whatnow.po
> +"internet üzerindeki diğer Python'la alakalı sitelere yönlendirmeler "
```suggestion
"Python ile ilgili diğer internet sitelerine yönlendirmeler "
```

2022-01-07 16:39 UTC, Ardasak commented on tutorial/whatnow.po
> +"Paket Dizini, kullanıcılar tarafından oluşturulan ve indirilebilen Python "
```suggestion
"Paket Dizini, kullanıcılar tarafından oluşturulan indirilebilir Python "
```

2022-01-07 16:39 UTC, Ardasak commented on tutorial/whatnow.po
> +"soruların çoğunu yanıtlar ve sorununuz için çözümü içerebilir."
```suggestion
"soruların çoğunu yanıtlar ve halihazırda sorununuzun çözümünü içeriyor olabilir."
```

2022-01-07 16:39 UTC, Ardasak commented on tutorial/whatnow.po
> +"\"Cheese Shop\" bir Monty Python'un çizimidir: bir müşteri peynir dükkanına "
```suggestion
"\"Cheese Shop\" Monty Python'un bir çizimidir: bir müşteri peynir dükkanına "
```

2022-01-07 16:39 UTC, Ardasak commented on tutorial/whatnow.po
> +"çeşitli yerlerinde kopyalanır; bir mirror, coğrafi konumunuza bağlı olarak "
```suggestion
"çeşitli yerlerinde kopyalanır; bir kopya, coğrafi konumunuza bağlı olarak "
```

2022-01-07 17:47 UTC, egeakman commented on .github/workflows/wrap.yml
> +        run: git pull origin ${{ github.event.pull_request.head.ref }}
```suggestion
```

2022-01-07 17:49 UTC, egeakman approved these changes

2022-01-07 19:17 UTC, Ardasak approved these changes

2022-01-07 19:28 UTC, merged