translated tutorial/appetite
python-docs-tr/python-docs-tr pull request #15
Opened 2022-01-07 19:26 UTC by Bengisuyarbas

2022-01-07 20:05 UTC, egeakman requested changes
@sefikaozturk 115. satırdan sonrasını sen yapabilir misin?

2022-01-07 20:05 UTC, egeakman commented on tutorial/appetite.po
> +"istemiyorsunuz."
```suggestion
"Profesyonel bir yazılım geliştiricisiyseniz, birçok C/C++/Java kütüphanesiyle "
"çalışmanız gerekebilir, ancak normal yazma/derleme/test etme/yeniden derleme "
"döngüsünü çok yavaş buluyorsunuz.  Belki de böyle bir kütüphane için bir test "
"paketi yazıyorsunuz ve test kodunu yazmayı sıkıcı bir görev olarak "
"buluyorsunuz.  Veya eklenti dili kullanabilecek bir program "
"yazdınız ve uygulamanız için yepyeni bir dil tasarlamak ve uygulamak "
"istemiyorsunuz."
```

2022-01-07 20:05 UTC, egeakman commented on tutorial/appetite.po
> +"yardımcı olur."
```suggestion
"Bu görevlerden bazıları için bir Unix kabuk komut dosyası veya Windows toplu "
"iş dosyaları yazabilirsiniz, ancak kabuk komut dosyaları, dosyaların "
"etrafında hareket etmek ve metin verilerini değiştirmekte en iyisi olmakla beraber "
"GUI uygulamaları veya oyun yapımı için pek öyle olmayabilir. " 
"Bir C/C++/Java programı "
"yazabilirsiniz, ancak taslak programını almak bile çok zaman alabilir.  "
"Python'un kullanımı daha kolaydır, Windows, macOS ve Unix işletim "
"sistemlerinde kullanılabilir ve işi daha hızlı bir şekilde halletmenize "
"yardımcı olur."
```

2022-01-07 20:05 UTC, egeakman commented on tutorial/appetite.po
> +"bu dillerdeki kadar kolaydır."
```suggestion
"Python kolay olmakla birlikte, kabuk komut dosyalarının veya toplu iş "
"dosyalarının sunabileceğinden çok daha fazla yapı ve büyük programlar için "
"destek sunan gerçek bir programlama dilidir.  Öte yandan, Python "
"C'den çok daha fazla hata denetimi sunar ve *çok üst düzey bir dil (very-high-level language)* olarak, "
"esnek diziler ve sözlükler gibi yerleşik üst düzey veri türlerine sahiptir.  "
"Python daha genel veri türleri nedeniyle, Awk ve hatta Perl'den "
"çok daha büyük bir kullanım alanına uygulanabilir, ancak Python'da birçok "
"şey en az bu dillerdeki kadar kolaydır."
```

2022-01-07 20:05 UTC, egeakman commented on tutorial/appetite.po
> +"gibi grafik kullanıcı arayüzü araç setlerine arayüzler gibi şeyler sağlar."
```suggestion
"Python, programınızı diğer Python programlarında yeniden kullanılabilecek "
"modüllere bölmenizi sağlar. Python, programlayı öğrenmeye "
"başlarken veya programlarınızda temel olarak "
"kullanabileceğiniz geniş bir standart modül koleksiyonuyla birlikte gelir.  "
"Bu modüllerden bazıları dosya giriş/çıkışı (I/O), sistem çağrıları, soketler ve hatta Tk "
"gibi GUI araç setleri içerir."
```

2022-01-17 18:40 UTC, sefikaozturk requested changes

2022-01-17 18:40 UTC, sefikaozturk commented on tutorial/appetite.po
> +"sırasında işlevleri test etmeyi kolaylaştırır. Ayrıca kullanışlı bir masa "
```suggestion
"sırasında işlevleri test etmeyi kolaylaştırır. Ayrıca kullanışlı bir masa üstü"
```

2022-01-17 18:40 UTC, sefikaozturk commented on tutorial/appetite.po
> +"C, C++ veya Java programlarına göre çok daha kısadır:"
```suggestion
"Python'da yazılan programlar genellikle çeşitli nedenlerden dolayı aynı görevi gören "
"C, C++ veya Java programlarına göre çok daha kısadır:"
```

2022-01-17 18:40 UTC, sefikaozturk commented on tutorial/appetite.po
> +"ile yapılır;"
```suggestion
"ifade gruplandırması, başlangıç ve bitişe koyulan köşeli ayraçlar yerine girintileme kullanılarak "
"yapılır;"
```

2022-01-17 18:40 UTC, sefikaozturk commented on tutorial/appetite.po
> +"skeçlerine atıfta bulunmak sadece izin verilmez, aynı zaman teşvik edilir!"
```suggestion
"Bu arada, dil adını BBC şovu \"Monty Python'un Uçan Sirki\"nden "
"almıştır ve sürüngenlerle hiçbir ilgisi yoktur.  Belgelerde Monty Python "
"skeçlerine atıfta bulunmaya sadece izin verilmez, aynı zamanda teşvik edilir!"
```

2022-01-17 18:40 UTC, sefikaozturk commented on tutorial/appetite.po
> +"Artık hepiniz Python için heyecanlısınız, biraz daha ayrıntılı olarak "
```suggestion
"Artık hepiniz Python için heyecanlı olduğunuza göre, biraz daha ayrıntılı olarak "
```

2022-01-17 18:40 UTC, sefikaozturk commented on tutorial/appetite.po
> +"Bir sonraki bölümde, tercümanı kullanma mekaniği açıklanmıştır.  Bu oldukça "
```suggestion
"Bir sonraki bölümde, yorumlayıcıyı kullanma mekaniği açıklanmıştır.  Bu oldukça "
```

2022-01-17 18:40 UTC, sefikaozturk commented on tutorial/whatnow.po
> +"modülleri dizinidir.  Kodu yayınlamaya başladıktan sonra, başkalarının "
```suggestion
"modülleri dizinidir.  Kodlarınızı yayınlamaya başladıktan sonra, başkalarının "
```

2022-01-17 18:52 UTC, egeakman approved these changes

2022-01-17 19:09 UTC, sefikaozturk approved these changes

2022-01-17 19:10 UTC, egeakman commented
ready to merge!

2022-01-17 19:10 UTC, merged