tutorial/appendix
python-docs-tr/python-docs-tr pull request #17
Opened 2022-01-10 15:56 UTC by Bengisuyarbas

2022-01-12 22:03 UTC, Ardasak requested changes
After @egeakman also reviews, we could change these. Good job!!

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +msgstr "Ek"
```suggestion
msgstr "Ek Bölüm"
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"durumuyla çıkar. (:keyword:'try' deyimindeki :keyword:'except' yan tümcesi "
```suggestion
"veri giriş gercekleştiğinde, yığın izlemeyi yazdırdıktan sonra sıfır olmayan bir çıkış "
"koduyla çıkar. (:keyword:'try' deyimindeki :keyword:'except' yan tümcesi "
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"koşulsuz olarak ölümcüldür ve sıfır olmayan bir çıkışla çıkışa neden olur; "
```suggestion
"koşulsuz olarak ölümcüldür ve sıfır olmayan bir çıkış koduyla çıkışa neden olur; "
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"işlenebilir."
```suggestion
"Yarıda kesme karakterinin (genellikle :kbd:'Control-C' veya :kbd:'Delete') birincil "
"veya ikincil istemine yazılması girişi iptal eder ve birincil istemi döndürür. "
"[#]_ Bir komut yürütülürken bir yarıda kesme karakteri yazmak:exc:'KeyboardInterrupt' özel "
"durumuna neden olur ve bu özel durum :keyword:'try' deyimi tarafından "
"işlenebilir."
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"yazdırır. Etkileşimli modda, daha sonra birincil isteme döner; bir dosyadan "
```suggestion
"yazdırır. Etkileşimli modda, daha sonra birincil istemi döndürür; bir dosyadan "
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"bu, iç tutarsızlıklar ve belleğin tükendiklerine ilişkin bazı durumlar için "
```suggestion
"bu, iç tutarsızlıklar ve belleğin tükendiğine ilişkin bazı durumlar için "
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"BSD'ish Unix sistemlerinde Python komut dosyaları, :: satırı koyarak kabuk "
```suggestion
"BSD türü Unix sistemlerinde Python komut dosyaları, :: satırı koyarak kabuk "
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"Komut dosyasına :p rogram:'chmod' komutu kullanılarak yürütülebilir mod veya "
```suggestion
"Komut dosyasına :program:`chmod` komutu kullanılarak yürütülebilir mod veya "
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"karakteri olan '''#''' kullanıldığını unutmayın."
```suggestion
"(yorumlayıcının kullanıcının :envvar:'PATH') komut dosyasının başında "
"olduğunu ve dosyaya yürütülebilir bir mod verdiğini varsayarsak.  ''#!'' "
"dosyanın ilk iki karakteri olmalıdır.  Bazı platformlarda, bu ilk satırın "
"Windows (``'\\r\\n'``) satır sonuyla değil, Unix stili bir satır sonuyla "
"(``\\n'``) bitmesi gerekir.  Python'da yorum başlatmak için karma veya pound "
"karakteri olan ``'#'`` kullanıldığını unutmayın."
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"konsol penceresi bastırılır."
```suggestion
"yükleyicisi otomatik olarak ``.py`` dosyalarını ``python.exe`` ile "
"ilişkilendirir, böylece python dosyasına çift tıklama komut dosyası olarak "
"çalıştırılır.  Uzantı ``.pyw`` 'de olabilir, bu durumda normalde görünen "
"konsol penceresi bastırılır."
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"file:'.profile' özelliğine benzer."
```suggestion
"Python'u etkileşimli olarak kullandığınızda, yorumlayıcı her başlatıldığında "
"bazı standart komutların yürütülmesi genellikle kullanışlıdır.  Bunu, "
"başlatma komutlarınızı içeren bir dosyanın adına :envvar:`PYTHONSTARTUP` "
"adlı bir ortam değişkeni ayarlayarak yapabilirsiniz.  Bu, Unix kabuklarının :"
"file:`.profile` özelliğine benzer."
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"de değiştirebilirsiniz."
```suggestion
"Bu dosya Python komutları bir komut "
"dosyasından okuduğunda değil, yalnızca etkileşimli oturumlarda okunur. Python komutları bir komut "
"dosyasından okuduğunda, :file:`/dev/tty` komutların açık kaynağı "
"olarak verildiğinde değil (aksi takdirde etkileşimli bir oturum gibi "
"davranır).  Etkileşimli komutların yürütüldüğü aynı ad alanında yürütülür, "
"böylece tanımladığı veya aldığı nesneler etkileşimli oturumda nitelik "
"olmadan kullanılabilir. Bu dosyadaki ``sys.ps1`` ve ``sys.ps2`` istemlerini "
"de değiştirebilirsiniz."
```

@egeakman buranın yazımını biraz düzeltirsin kardesim yatmam lazım yakında

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"Python'ı başlatın ve şu kodu çalıştırın::"
```suggestion
"Python özelleştirmenize izin vermek için iki kanca sağlar: :"
"mod:`sitecustomize` ve :mod:`usercustomize`.  Nasıl çalıştığını görmek için "
"önce kullanıcı sitesi paketleri dizininizin konumunu bulmanız gerekir.  "
"Python'ı başlatın ve şu kodu çalıştırın::"
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"modülünün belgelerine bakın."
```suggestion
":mod:`sitecustomize` aynı şekilde çalışır, ancak genellikle genel site "
"paketleri dizinindeki bilgisayarın yöneticisi tarafından oluşturulur ve :"
"mod:`usercustomize` 'den önce alınır.  Daha fazla ayrıntı için :mod:`site` "
"modülünün belgelerine bakın."
```

2022-01-12 22:03 UTC, Ardasak commented on tutorial/appendix.po
> +"dosyasında açıkça yapmalısınız::"
```suggestion
"Geçerli dizinden ek bir başlangıç dosyası okumak istiyorsanız, bunu genel "
"başlangıç dosyasında ``if os.path.isfile('.pythonrc.py'): exec(open('."
"pythonrc.py').read()`` gibi bir kod kullanarak programlayabilirsiniz. "
"Başlangıç dosyasını bir komut dosyasında kullanmak istiyorsanız, bunu komut "
"dosyasında açıkça yapmalısınız::"
```

2022-01-16 14:43 UTC, Ardasak approved these changes

2022-01-16 14:53 UTC, egeakman requested changes

2022-01-16 14:53 UTC, egeakman commented on tutorial/appendix.po
> +"koduyla çıkar. (:keyword:'try' deyimindeki :keyword:'except' yan tümcesi "
```suggestion
"koduyla çıkar. (:keyword:`try` deyimindeki :keyword:`except` yan tümcesi "
```

2022-01-16 14:53 UTC, egeakman commented on tutorial/appendix.po
> +"Yarıda kesme karakterinin (genellikle :kbd:'Control-C' veya :kbd:'Delete') birincil "
```suggestion
"Yarıda kesme karakterinin (genellikle :kbd:`Control-C` veya :kbd:`Delete`) birincil "
```

2022-01-16 14:53 UTC, egeakman commented on tutorial/appendix.po
> +"olduğunu ve dosyaya yürütülebilir bir mod verdiğini varsayarsak.  ''#!'' "
```suggestion
"(yorumlayıcının kullanıcının :envvar:`PATH`) komut dosyasının başında "
"olduğunu ve dosyaya yürütülebilir bir mod verdiğini varsayarsak.  ``#!`` "
```

2022-01-16 14:53 UTC, egeakman commented on tutorial/appendix.po
> +"çağrısını etkiler."
```suggestion
"Artık bu dizinde :file:`usercustomize.py` adlı bir dosya oluşturabilir ve "
"içine istediğiniz her şeyi koyabilirsiniz.  Otomatik içe aktarmayı devre "
"dışı bırakmak için :option:`-s` seçeneğiyle başlatılmadıkça Python'un her "
"çağrısını etkiler."
```

2022-01-16 14:53 UTC, egeakman commented on tutorial/appendix.po
> +"mod:`usercustomize` 'den önce alınır.  Daha fazla ayrıntı için :mod:`site` "
```suggestion
"mod:`usercustomize` 'dan önce alınır.  Daha fazla ayrıntı için :mod:`site` "
```

a.

2022-01-16 15:04 UTC, Ardasak commented
@egeakman a.

2022-01-16 15:29 UTC, egeakman approved these changes

2022-01-16 16:20 UTC, Ardasak approved these changes
@Bengisuyarbas sen dünyanın en adam adamısın

2022-01-16 16:21 UTC, merged