distutils/index, distributing/index
python-docs-tr/python-docs-tr pull request #19
Opened 2022-01-11 15:16 UTC by irfan-karabacak

distutils/index is translated.

2022-01-16 15:00 UTC, egeakman commented
It looks like distributing/index has also been translated. Wrong branch but good job tho

2022-01-23 23:35 UTC, Ardasak requested changes
Sen adamsın ya

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"kullanıcılar topluluğuna sahiptir."
```suggestion
"Popüler bir açık kaynak geliştirme projesi olarak Python, yazılımlarını "
"diğer Python geliştiricilerinin açık kaynak lisans koşulları altında "
"kullanmasını sağlayan, aktif bir şekilde destek veren katkıda bulunanlar ve "
"kullanıcılar topluluğuna sahiptir."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"yapmalarına olanak tanır."
```suggestion
"Bu, Python kullanıcılarının, ortak havuza kendi çözümleriyle potansiyel "
"olarak katkıda bulunmanın yanı sıra, ortak (ve hatta bazen nadir!) sorunlara "
"karşı halihazırda oluşturdukları çözümlerden yararlanarak, Python "
"kullanıcılarının etkin bir şekilde paylaşımda bulunmalarına ve işbirliği "
"yapmalarına olanak tanır."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"kullanırken lütfen bu tür politikaları dikkate alın."
```suggestion
"Kurumsal kullanıcılar için, birçok kuruluşun açık kaynaklı "
"yazılımları kullanma ve bunlara katkıda bulunma konusunda kendi politikaları "
"olduğunu unutmayın. Python ile sağlanan dağıtım ve kurulum araçlarını "
"kullanırken lütfen bu tür politikaları dikkate alın."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"bir yazılım havuzudur."
```suggestion
"`Python Package Index <https://pypi.org>`__ , diğer Python kullanıcıları "
"tarafından kullanıma sunulan açık kaynaklı lisanslı paketlerin "
"bir yazılım deposudur."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"izleyicileri bulundururlar."
```suggestion
"`Python Packaging Authority <https://www.pypa.io/>`__ , standart paketleme "
"araçlarının, ilgili meta verinin ve dosya formatı standartlarının bakımından "
"ve geliştirilmesinden sorumlu geliştiriciler ve dokümantasyon yazarları grubudur. "
"Hem `GitHub <https://github.com/pypa>`__ hem de `Bitbucket <https://"
"bitbucket.org/pypa/>`__ üzerinde çeşitli araçlar, dokümantasyon ve sorun "
"izleyicileri bulundururlar."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"adı gibi)."
```suggestion
":mod:`distutils`, Python standart kitaplığına ilk kez 1998 yılında eklenen "
"orijinal derleme ve dağıtım sistemidir. :mod:`distutils`in doğrudan "
"kullanımı aşamalı olarak kaldırılırken, halen mevcut paketleme ve dağıtım "
"altyapısının temelini atmıştır. Yalnızca standart kitaplığın bir parçası "
"olmakla kalmaz, adı başka şekillerde de yaşar (Python paketleme "
"standartları geliştirmeyi koordine etmek için kullanılan posta listesinin "
"adı gibi)."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"tanımlanır) üretir."
```suggestion
"`wheel`_ (bu bağlamda), ``bdist_wheel`` komutunu :mod:`distutils`/"
"`setuptools`_ dizinine ekleyen bir projedir. Bu, Python kütüphanelerinin, "
"(ikili uzantıları içerenlerin bile) bir sisteme yerel olarak kurulmasına "
"gerek kalmadan kurulmasına izin veren bir çapraz platform ikili paketleme "
"biçimi (\"wheels\" veya \"wheel files\" olarak adlandırılır ve :pep:`427`de "
"tanımlanır) üretir."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"ilgili çeşitli temel adımları ve öğeleri kapsar:"
```suggestion
"Python Paketleme Kullanıcı Kılavuzu, bir proje oluşturma ve yayınlamayla "
"ilgili çeşitli temel adımları ve öğeleri kapsar:"
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +msgstr "Nasıl yapabilirim...?"
```suggestion
msgstr "Nasıl yaparım...?"
```

kalıp olarak böyle daha mantıklı oluyor

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"gibi popüler barındırma sitelerini kontrol edin."
```suggestion
"Bu ada sahip bir proje olup olmadığını görmek için GitHub, Bitbucket vb. "
"popüler barındırma sitelerini kontrol edin."
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"özellikle birden çok anlamı olan özellikle yaygın sözcüklerden kaçının"
```suggestion
"kullanıcıların yazılımınızı ararken bulmasını zorlaştırabileceğinden, "
"özellikle birden çok anlamı olan yaygın sözcüklerden kaçının"
```

2022-01-23 23:35 UTC, Ardasak commented on distributing/index.po
> +"`Python Packaging User Guide: Binary Extensions <https://packaging.python."
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantılar <https://packaging.python."
```

2022-01-24 06:50 UTC, irfan-karabacak commented on distributing/index.po
> +"izleyicileri bulundururlar."
dokümantasyonu özellikle bir kalıp olarak kullandım çünkü çok yer geçiyor, bundan sonra belge mi kullanayım

2022-01-24 14:32 UTC, egeakman commented on distributing/index.po
> +"gibi popüler barındırma sitelerini kontrol edin."
Olduğu gibi kalabilir bence ya

2022-01-24 14:47 UTC, egeakman requested changes

2022-01-24 14:47 UTC, egeakman commented on distutils/index.po
> +"deprecated>` girişine bakın."
```suggestion
"Tüm ``distutils`` paketi artık kullanılmamaktadır ve Python 3.12'de tamamen "
"kaldırılacaktır. Bu dokümantasyon yalnızca referans olarak tutulur ve paketin kaldırılmasıyla "
"birlikte bu belge de kaldırılacaktır. Daha fazla bilgi için :ref:`What's New <distutils-"
"deprecated>` girişine bakın."
```

2022-01-24 14:47 UTC, egeakman commented on distutils/index.po
> +"ilgili tüm bilgileri bağımsız olarak kapsayasına kadar saklanacaktır."
```suggestion
"Bu dokümantasyon, https://setuptools.readthedocs.io/en/latest/setuptools.html "
"adresindeki ``setuptools`` dokümantasyonu burada bulunan "
"tüm bilgileri kapsayana kadar saklanacaktır."
```

2022-01-24 14:47 UTC, egeakman commented on distutils/index.po
> +"recommendations/>`__ 'a bakın."
```suggestion
"Bu rehber yalnızca, Python'un bu sürümünün bir parçası olarak sağlanan "
"uzantıları oluşturmaya ve dağıtmaya yönelik temel araçları kapsar. Üçüncü "
"taraf araçlar, kullanımı daha kolay ve daha güvenli alternatifler sunar. "
"Daha fazla bilgi için Python Paketleme Kullanıcı Kılavuzundaki "
"`hızlı tavsiyeler bölümüne <https://packaging.python.org/guides/tool-"
"recommendations/>`__  bakın."
```

2022-01-24 14:47 UTC, egeakman commented on distutils/index.po
> +"işlevlerini açıklar."
```suggestion
"getirmesine olanak sağlamak amacıyla ``setuptools`` 'un geliştirdiği temel "
"işlevleri açıklar."
```

2022-01-24 14:51 UTC, egeakman approved these changes
LGTM 👍

2022-01-24 15:23 UTC, merged