tutorial/errors
python-docs-tr/python-docs-tr pull request #22
Opened 2022-02-20 16:40 UTC by Bengisuyarbas

2022-02-24 12:16 UTC, egeakman commented on tutorial/errors.po
> +"Language-Team: TURKISH < python.docs.tr@gmail.com >\n"
```suggestion
"Language-Team: TURKISH <python.docs.tr@gmail.com>\n"
```

2022-02-24 12:16 UTC, egeakman commented on tutorial/errors.po
> +"edilebilir hata türü vardır: *sözdizimi hataları* ve *özel durumlar*."
```suggestion
"Şimdiye kadar hata mesajlarından fazla bahsedilmedi, ancak "
"örnekleri denediyseniz muhtemelen bazılarını görmüşsünüzdür.  (En azından) iki ayırt "
"edilebilir hata türü vardır: *sözdizimi hataları* (*syntax errors*) ve *özel durumlar* (*exceptions*)."
```

2022-02-24 12:16 UTC, egeakman commented on tutorial/errors.po
> +"belki de en sık karşılaşılan şikayet türüdir::"
```suggestion
"Ayrıştırma hataları olarak da bilinen söz dizimi hataları, Python öğrenirken "
"belki de en sık karşılaşılan hatalardan biridir::"
```

2022-02-24 12:16 UTC, egeakman commented on tutorial/errors.po
> +msgstr "Sözdizimi Hataları"
```suggestion
msgstr "Söz Dizimi Hataları"
```

2022-03-01 09:04 UTC, egeakman requested changes

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"bir komut dosyasından gelmesi durumunda nereye bakacağınızı bilirsiniz."
```suggestion
"Ayrıştırıcı, hatalı satırı yineler ve hatanın algılandığı "
"en erken noktayı gösteren küçük bir 'ok' görüntüler. "
"Hata oktan *önceki* dizgede meydana  gelmiştir: örnekte, "
"hata :func:`print` fonksiyonunda algılanır, çünkü öncesinde iki nokta üst üste "
"(``":"``) eksiktir.  Dosya adı ve satır numarası yazdırılır, böylece girişin "
"bir komut dosyasından gelmesi durumunda nereye bakacağınızı bilirsiniz."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"iletileriyle sonuçlanıyor::"
```suggestion
"Bir komut veya ifade söz dizimsel olarak doğru olsa bile, yürütülmeye "
"çalışıldığında hataya neden olabilir. Yürütme sırasında algılanan hatalara "
"*exceptions (özel durumlar)* denir ve bazıları programlar için kritik değildir: yakında Python "
"programlarında bunların üstesinden gelmeyi öğreneceksiniz.  Ancak, çoğu "
"özel durum programlar tarafından önlenemez ve burada gösterildiği gibi hata "
"iletileriyle sonuçlanır::"
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"tanımlayıcılardır (ayrılmış anahtar sözcükler değildir)."
```suggestion
"Hata iletisinin son satırı hataya neyin sebep olduğu gösterir. Özel durumlar farklı "
"türlerde gelir ve tür iletinin bir parçası olarak yazdırılır: örnekteki "
"türler şunlardır: exc:`ZeroDivisionError`, :exc:`NameError` ve :"
"exc:`TypeError`. Özel durum türü olarak yazdırılan dize, oluşan gömülü "
"özel durumun adıdır.  Bu, tüm gömülü özel durumlar için geçerlidir, ancak "
"kullanıcı tanımlı özel durumlar için doğru olması gerekmez (yararlı bir "
"kural olmasına rağmen). Standart özel durum adları gömülü "
"tanımlayıcılardır (ayrılmış anahtar sözcükler değildir)."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +":ref:'bltin-exceptions' yerleşik özel durumları ve anlamlarını listeler."
```suggestion
":ref:`bltin-exceptions` yerleşik özel durumları ve anlamlarını listeler."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"işaretlendiğini unutmayın. ::"
```suggestion
"Seçili özel durumları işleyen programlar yazmak mümkündür. Geçerli bir "
"tam sayı girilene kadar kullanıcıdan giriş isteyen, ancak kullanıcının "
"programı kesmesine izin veren aşağıdaki örneğe bakın (:kbd:`Control-C` veya "
"işletim sistemi ne destekliyorsa onu kullanarak); kullanıcı kaynaklı kesintilerin "
":exc:`KeyboardInterrupt` özel durumu ile gösterildiğini unutmayın::
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +msgstr ":keyword:'try' ifadesi aşağıdaki gibi çalışır."
```suggestion
msgstr ":keyword:`try` ifadesi aşağıdaki gibi çalışır."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"sözcükleri arasındaki ifadeler) yürütülür."
```suggestion
"İlk olarak, *try yan tümcesi* (:keyword:`try` ve :keyword:`except` anahtar "
"kelimeleri arasındaki ifadeler) yürütülür."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"ifadesinin yürütülmesi tamamlanır."
```suggestion
"Özel durum oluşmazsa, *except yan tümcesi* atlanır ve :keyword:`try` "
"ifadesinin yürütülmesi tamamlanır."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"yürütülür ve deneme/hariç bloğundan sonra yürütme devam eder."
```suggestion
":keyword:`try` yan tümcesinin yürütülmesi sırasında bir özel durum oluşursa, "
"yan tümcenin geri kalanı atlanır.  Daha sonra belirtilen :keyword:`except` türü "
"ile karşılaşılırsa, *except yan tümcesi* "
"yürütülür ve try/except bloğundan sonra yürütme devam eder."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"iletiyle durur."
```suggestion
"oluşursa, daha dışarıda olan :keyword:'try' ifadelerine geçirilir; işleyici bulunamazsa, bu "
"bir *işlenmeyen özel durum* olur ve yürütme yukarıda gösterildiği gibi bir "
"iletiyle durur."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"adlandırabilir, örneğin::"
```suggestion
":keyword:`try` ifadesi, farklı özel durumlar için işleyiciler belirtmek "
"üzere birden fazla *except yan tümcesi* alabilir.  Maksimum bir tane işleyici "
"yürütülür. İşleyiciler yalnızca karşılık gelen *try yan tümcesinde* oluşan "
"özel durumları işler, aynı :keyword:`!try` ifadesinin diğer işleyicilerinde "
"işlemez.  *except yan tümcesi* birden çok özel durumu parantezli demet olarak "
"adlandırabilir, örneğin::"
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"aşağıdaki kod B, C, D'yi bu sırada yazdırır::"
```suggestion
":keyword:`except` yan tümcesi, aynı sınıf veya temel sınıf ise özel "
"durum ile uyumludur (ancak türetilmiş bir sınıfı listeleyen *except yan "
"tümcesi* temel sınıfla uyumlu olmadığından  tersi olamaz). Örneğin, "
"aşağıdaki kod B, C, D'yi bu sırada yazdırır::"
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"yazdırılacaktır --- ilk eşleşen *except yan tümcesi* tetiklenir."
```suggestion
"*except yan tümceleri* tersine çevrilmişse (ilk olarak ``except B`` ile) B, B, B şeklinde "
"yazdırılacaktır --- ilk eşleşen *except yan tümcesi* tetiklenir."
```

2022-03-01 09:04 UTC, egeakman commented on tutorial/errors.po
> +"kullanılabilir (arayanın özel durumu işlemesine izin vermek)::"
```suggestion
"Tüm özel durumlar :exc:`BaseException` 'dan kalıt alınır ve böylece joker karakter "
"olarak kullanılabilir. Bunu çok dikkatli kullanın, çünkü gerçek bir "
"programlama hatasını bu şekilde maskelemek kolaydır!  Ayrıca, bir hata "
"iletisi yazdırmak ve sonra özel durumu yeniden yükseltmek için de "
"kullanılabilir (çağıranın özel durumu işlemesine izin vermek)::"
```

2022-03-01 10:28 UTC, egeakman commented on tutorial/errors.po
> +"(``":"``) eksiktir.  Dosya adı ve satır numarası yazdırılır, böylece girişin "
```suggestion
"(``':'``) eksiktir.  Dosya adı ve satır numarası yazdırılır, böylece girişin "
```

2022-03-01 10:31 UTC, egeakman commented on tutorial/errors.po
> +":exc:`KeyboardInterrupt` özel durumu ile gösterildiğini unutmayın::
```suggestion
":exc:`KeyboardInterrupt` özel durumu ile gösterildiğini unutmayın. ::"
```

2022-04-25 21:45 UTC, Ardasak requested changes
h.o

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"alınmalıdır."
```suggestion
"Alternatif olarak, son özel durum yan tümcesi özel durum ad(ları)nı "
"atlayabilir, ancak özel durum değeri daha sonra ``sys.exc_info()[1]`` 'den "
"alınmalıdır."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"gereken kod için yararlıdır. Mesela::"
```suggestion
":keyword:`try` ... :keyword:`except` ifadesinin isteğe bağlı bir *else yan "
"tümcesi* vardır, bu da mevcut olduğunda tüm *except yan tümcelerini* "
"izlemelidir.  *try yan tümcesi* bir özel durum oluşturmazsa yürütülmesi "
"gereken kod için yararlıdır. Mesela::"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"deneyin` ... :anahtar kelime:`!hariç` ifadesi."
```suggestion
":keyword:`!else` yan tümcesinin kullanılması, :keyword:`try` yan tümcesine "
"ek kod eklemekten daha iyidir çünkü yanlışlıkla :keyword:`!try` tarafından "
"korunan kod tarafından oluşturulmamış bir istisnayı yakalamayı önler."
" ... :keyword:`!except` ifadesi."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"başlatabilir ve istendiği gibi ona herhangi bir nitelik ekleyebilir. ::"
```suggestion
"*except yan tümcesi*, istisna adından sonra bir değişken belirtebilir. "
"Değişken, ``instance.args`` içinde depolanan bağımsız değişkenlerle bir istisna "
"örneğine bağlıdır. Kolaylık sağlamak için, istisna örneği :meth:`__str__` "
"öğesini tanımlar, böylece argümanlar ``.args`` öğesine başvurmak zorunda "
"kalmadan doğrudan yazdırılabilir. Ayrıca, bir istisna, onu yükseltmeden önce "
"başlatabilir ve istendiği gibi ona herhangi bir nitelik ekleyebilir. ::"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +msgstr "Özel Durumları Yükseltme"
```suggestion
msgstr "Hata Ortaya Çıkartma"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"bir sınıf) olmalıdır. Bir istisna sınıfı iletilirse, yapıcısı hiçbir argüman "
```suggestion
"bir sınıf) olmalıdır. Argüman verilmezse, yapıcısı hiçbir argüman "
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +msgstr "Özel Durum Zincirleme"
```suggestion
msgstr "İstisna Zincirleme"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"biçimi, istisnayı yeniden oluşturmanıza olanak tanır::"
```suggestion
"Bir istisnanın oluşturulup oluşturulmadığını belirlemeniz gerekiyorsa ancak "
"onu işlemeyi düşünmüyorsanız, :keyword:`raise` ifadesinin daha basit bir "
"biçimi, istisnayı yeniden oluşturmanıza olanak tanır::"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"keyword:`from<raise>`e izin verir. Örneğin::"
```suggestion
":keyword:`raise` ifadesi, zincirleme istisnalar sağlayan opsiyonel bir :"
"keyword:`from<raise>`e izin verir. Örneğin::"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"None`` deyimi kullanılarak devre dışı bırakılabilir:"
```suggestion
"İstisna zincirlemesi, bir :keyword:`except` veya :keyword:`finally` "
"bölümünde bir istisna açıldığında otomatik olarak gerçekleşir. Bu, ``from "
"None`` deyimi kullanılarak devre dışı bırakılabilir:"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +msgstr "Kullanıcı Tanımlı Özel Durumlar"
```suggestion
msgstr "Kullanıcı Tanımlı İstisnalar"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"exc:'Exception' sınıfından türetilmelidir."
```suggestion
"Programlar yeni bir istisna sınıfı oluşturarak kendi özel durumlarını "
"adlandırabilir (Python sınıfları hakkında daha fazla bilgi için bkz: :ref:"
"`tut-classes` ).  Özel durumlar genellikle doğrudan veya dolaylı olarak :"
"exc:`Exception` sınıfından türetilmelidir."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"durum sınıfları oluşturmak için bir alt sınıf oluşturmaktır::"
```suggestion
"İstisna sınıfları, başka bir sınıfın yapabileceği her şeyi yapan sınıflar"
"olarak tanımlanabilir, ancak genellikle basit tutulur, genellikle yalnızca hata "
"hakkındaki bilgilerin özel durum için işleyiciler tarafından ayıklanmasına "
"izin veren bir dizi özellik sunar.  Birkaç farklı hata oluşturabilecek bir "
"modül oluştururken, yaygın bir uygulama, bu modül tarafından tanımlanan özel "
"durumlar için bir temel sınıf ve farklı hata koşulları için belirli özel "
"durum sınıfları oluşturmak için bir alt sınıf oluşturmaktır::"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"bilgi :ref:`tut-classes` bölümünde sunulmaktadır."
```suggestion
"Birçok standart modül, tanımladıkları işlevlerde oluşabilecek hataları "
"bildirmek için kendi istisnalarını tanımlar.  Dersler hakkında daha fazla "
"bilgi :ref:`tut-classes` bölümünde sunulmaktadır."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"sahiptir.  Mesela::"
```suggestion
":keyword:`!try` deyimi, her koşulda yürütülmesi gereken temizleme "
"eylemlerini tanımlamayı amaçlayan başka bir opsiyonel yan tümceye "
"sahiptir.  Mesela::"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"oluştuğunda daha karmaşık durumlar anlatılmaktadır:"
```suggestion
"Bir :keyword:`finally` yan tümcesi varsa, :keyword:`finally` yan tümcesi :"
"keyword:`try` deyimi tamamlanmadan önceki son görev olarak yürütülür. :"
"keyword:`!finally` yan tümcesi :keyword:`!try` deyiminin bir istisna "
"oluşturup oluşturmadığından bağımsız çalışır. Aşağıdaki noktalarda, bir istisna "
"oluştuğunda daha karmaşık durumlar anlatılmaktadır:"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"yeniden oluşturulur"
```suggestion
":keyword:`!try` yan tümcesinin yürütülmesi sırasında bir istisna "
"oluşursa, istisna bir :keyword:`except` yan tümcesi tarafından "
"işlenebilir. İstisna bir :keyword:`!except` yan tümcesi tarafından ele "
"alınmıyorsa, istisna :keyword:`!finally` yan tümcesi yürütüldükten sonra "
"yeniden oluşturulur."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"yürütülmesinin hemen öncesinde yürütülür ."
```suggestion
":keyword:`!try` ifadesi bir :keyword:`break`, :keyword:`continue` veya :"
"keyword:`return` ifadesine ulaşırsa, :keyword:`!finally` yan tümcesi :"
"keyword:`!break`, :keyword:`!continue` veya :keyword:`!return` ifadesinin "
"yürütülmesinin hemen öncesinde yürütülür."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"keyword:`!return` ifadesindeki değer değil."
```suggestion
"Bir :keyword:`!finally` yan tümcesi bir :keyword:`!return` ifadesini "
"içeriyorsa, döndürülen değer, :keyword:`!finally` yan tümcesinin :keyword:`!"
"return` ifadesindeki değer olacaktır, :keyword:`!try` yan tümcesinin :"
"keyword:`!return` ifadesindeki değer değil."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"yürütüldikten sonra yeniden yükseltildi."
```suggestion
"Gördüğünüz gibi, :keyword:`finally` yan tümcesi her durumda yürütülür.  İki "
"dizeyi bölerek oluşturulan :exc:`TypeError`, :keyword:`except` yan tümcesi "
"tarafından işlenmez ve bu nedenle :keyword:`!finally` yan tümcesi "
"yürütüldikten sonra yeniden yükseltilir."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"veya ağ bağlantıları gibi) serbest bırakmak için yararlıdır."
```suggestion
"Gerçek dünyadaki uygulamalarda: keyword:`finally` yan tümcesi, kaynağın "
"kullanımının başarılı olup olmadığına bakılmaksızın dış kaynakları (dosyalar "
"veya ağ bağlantıları gibi) serbest bırakmak için yararlıdır."
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"bir şekilde temizlenmesini sağlayacak şekilde kullanılmasına izin verir. ::"
```suggestion
"Bu kodla ilgili sorun, kodun bu bölümünün yürütülmesi tamamlandıktan sonra "
"dosyayı belirsiz bir süre açık bırakmasıdır. Bu basit komut dosyalarında bir "
"sorun değildir, ancak daha büyük uygulamalar için bir sorun olabilir. :"
"keyword:`with` ifadesi, dosyalar gibi nesnelerin her zaman hızlı ve doğru "
"temizlenmesini sağlayacak şekilde kullanılmasına izin verir. ::"
```

2022-04-25 21:45 UTC, Ardasak commented on tutorial/errors.po
> +"temizleme eylemleri sağlayan nesneler belgelerinde bunu gösterir."
```suggestion
"İfade çalıştırıldıktan sonra, satırlar işlenirken bir sorunla karşılaşılsa "
"bile *f* dosyası her zaman kapatılır. Dosyalar gibi önceden tanımlanmış "
"temizleme eylemleri sağlayan nesneler dokümantasyonlarında bunu gösterir."
```

2022-04-28 15:24 UTC, merged