Faq/qui is done
python-docs-tr/python-docs-tr pull request #24
Opened 2022-02-24 19:04 UTC by irfan-karabacak

Faq/qui is done

2022-02-24 19:05 UTC, egeakman commented
fuck u diye okudum @irfan-karabacak

2022-02-24 19:05 UTC, irfan-karabacak commented
Yapıp atmayı unuttuğum

2022-03-01 10:09 UTC, egeakman requested changes
kaliteli olmuş eline sağlık

2022-03-01 10:09 UTC, egeakman commented on faq/gui.po
> +msgstr "Grafik Kullanıcı Arabirimi SSS"
```suggestion
msgstr "Grafik Kullanıcı Arayüzü SSS"
```

2022-03-01 10:09 UTC, egeakman commented on faq/gui.po
> +"`Tcl/Tk ana sayfasına <https://www.tcl.tk>` bakın. Tcl/Tk, macOS, Windows ve "
```suggestion
"öğesi kümesine yönelik nesne yönelimli bir arayüz içerir. Bu muhtemelen "
"kurulumu ve kullanımı en kolay olanıdır (çünkü çoğu `binary distributions "
"<https://www.python.org/downloads/>`_ Python'da bulunur) ve kullanılandır. "
"Kaynak işaretçiler de dahil olmak üzere Tk hakkında daha fazla bilgi için "
"`Tcl/Tk ana sayfasına <https://www.tcl.tk>`_ bakın. Tcl/Tk, macOS, Windows ve "
```

2022-03-01 10:09 UTC, egeakman commented on faq/gui.po
> +"GuiProgramming#Cross-Platform_Frameworks>` ve `platform-specific <https://"
```suggestion
"GuiProgramming#Cross-Platform_Frameworks>`_ ve `platform-specific <https://"
```

2022-03-01 10:09 UTC, egeakman commented on faq/gui.po
> +"kaydetmenize olanak tanır. Bakınız :ref:`tkinter-file-handlers`."
```suggestion
"kaydetmenize olanak tanır. Bkz. :ref:`tkinter-file-handlers`"
```

2022-03-01 10:09 UTC, egeakman commented on faq/gui.po
> +"odak alma seçeneğine bakın)."
```suggestion
"sahip olmamasıdır. Focus komutu için Tk dokümantasyonuna bakın. Genellikle "
"Wigdet'lara tıklanılarak klavye odağı verilir (ancak etiketler için değil; "
"odak alma seçeneğine bakın)."
```

2022-03-01 11:47 UTC, Ardasak requested changes

2022-03-01 11:47 UTC, Ardasak commented on faq/gui.po
> +"GuiProgramming#Cross-Platform_Frameworks>` ve `platform-specific <https://"
```suggestion
"mevcuttur. Bir `cross-platform listesi <https://wiki.python.org/moin/"
"GuiProgramming#Cross-Platform_Frameworks>` ve `spesifik platform <https://"
```

2022-03-01 11:47 UTC, Ardasak commented on faq/gui.po
> +msgstr "Tkinter'da çalışmak için anahtar bağlamaları alamıyorum: neden?"
```suggestion
msgstr "Tkinter'da çalışmak için anahtar bağlamalarını alamıyorum: neden?"
```

2022-03-01 11:54 UTC, egeakman commented on faq/gui.po
> +"GuiProgramming#Cross-Platform_Frameworks>`_ ve `platform-specific <https://"
```suggestion
"mevcuttur. Bir `cross-platform listesi <https://wiki.python.org/moin/"
"GuiProgramming#Cross-Platform_Frameworks>` ve `spesifik platform <https://"
```

2022-03-01 11:55 UTC, egeakman commented on faq/gui.po
> +"GuiProgramming#Cross-Platform_Frameworks>`_ ve `platform-specific <https://"
resolves previous suggestion

2022-03-01 11:59 UTC, egeakman approved these changes

2022-03-01 12:01 UTC, merged