tutorial/index
python-docs-tr/python-docs-tr pull request #25
Opened 2022-02-27 17:12 UTC by KeroNar

2022-03-01 19:24 UTC, egeakman requested changes

2022-03-01 19:24 UTC, egeakman commented on tutorial/index.po
> +"Last-Translator: Kerem Sevgin <keremkerembaran@hotmail.com>\n"
```suggestion
"Last-Translator: \n"
```

2022-03-01 19:24 UTC, egeakman commented on tutorial/index.po
> +"derinlemesine kapsayan birkaç kitap da vardır."
```suggestion
"Standart nesnelerin ve modüllerin açıklaması için bkz. :ref:`reference-"
"index` dilin daha resmi bir tanımını verir.  Uzantıları C veya C++'ta yazmak "
"için: ref:`extending-index` ve :ref:`c-api-index` 'i okuyun. Python'ı "
"derinlemesine kapsayan birkaç kitap da vardır."
```

2022-03-01 19:34 UTC, irfan-karabacak requested changes
Bir takım noktalama ve imla hataları düzeltimi

2022-03-01 19:34 UTC, irfan-karabacak commented on tutorial/index.po
> +"olacaksınız."
```suggestion
"Bu öğretici kapsamlı olmaya ve her bir özelliği, hatta yaygın olarak "
"kullanılan her özelliği bile kapsamaya çalışmaz. Bunun yerine, Python'un en "
"dikkat çekici özelliklerinin çoğunu sunar ve size dilin tarzı hakkında iyi "
"bir fikir verecektir. Okuduktan sonra, Python modüllerini ve programlarını "
"okuyabilecek ve yazabileceksiniz ve :ref:`library-index` bölümünde açıklanan "
"çeşitli Python kütüphanesi modülleri hakkında daha fazla bilgi edinmeye hazır "
"olacaksınız."
```

2022-03-01 19:34 UTC, irfan-karabacak commented on tutorial/index.po
> +msgstr ":ref:'glossary' de göz atmaya değer."
```suggestion
msgstr :Ayrıca ref:`glossary` de göz atmaya değer."
```

2022-03-13 17:13 UTC, egeakman approved these changes

2022-04-02 12:16 UTC, merged