tutorial/interpreter
python-docs-tr/python-docs-tr pull request #26
Opened 2022-02-27 17:13 UTC by KeroNar

2022-03-13 15:46 UTC, irfan-karabacak submitted a review, later dismissed
Syntaxlere baktım daha çok.

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"Last-Translator: Kerem Sevgin <keremkerembaran@hotmail.com>\n"
```suggestion
"Last-Translator: \n"
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"bin' yazmak, komutu yazarak başlatmayı mümkün kılar:"
```suggestion
msgstr ""
"Python yorumlayıcısı genellikle mevcut olduğu makinelerde :file:`/usr/local/"
"bin/python3.10` 'a yüklenir; Unix kabuğunuzun arama çubuğuna :file:`/usr/local/"
"bin` yazmak, komutu yazarak başlatmayı mümkün kılar:"
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"alternatif konumdur.)"
```suggestion
msgstr ""
"kabuğa. [#]_ Yorumlayıcının bulunduğu dizinin seçimi bir yükleme seçeneği "
"olduğundan, başka yerler de kullanım mümkündür; yerel Python gurunuza veya sistem "
"yöneticinize danışın.  (Örneğin, :file:`/usr/local/python` popüler bir "
"alternatif konumdur.)"
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"Python'u başlatmanın diğer yolları için :ref:'setting-envvars'a bakın."
```suggestion
msgstr ""
"Python'ı :ref:`Microsoft Store <windows-store>` yüklediğiniz Windows "
"makinelerinde: file:`python3.10` komutu kullanılabilir. :ref:`py.exe "
"launcher <launcher>` başlatıcısı yüklüyse, :file:`py` komutunu kullanabilirsiniz. "
"Python'u başlatmanın diğer yolları için :ref:`setting-envvars` 'a bakın."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"yürütülebilir dosyasıyla çakışmaz."
```suggestion
msgstr ""
"Unix'te, Python 3.x yorumlayıcısı varsayılan olarak ``python`` adlı "
"yürütülebilir dosyayla yüklenmez, böylece aynı anda yüklenen bir Python 2.x "
"yürütülebilir dosyasıyla çakışmaz."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"dosyanın ikinci satırı olarak eklenmelidir.  Mesela::"
```suggestion
msgstr ""
"*ilk satır* kuralının bir istisnası, kaynak kodun :ref:`UNIX \"shebang\" "
"line <tut-scripts>` satırı ile başlamasıdır.  Bu durumda, kodlama bildirimi "
"dosyanın ikinci satırı olarak eklenmelidir.  Mesela::"
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"bileşenlerinden biridir."
```suggestion
"burada *kodlama*, Python tarafından desteklenen geçerli :mod:`codec` "
"bileşenlerinden biridir."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"olarak, şu :keyword:'if' deyimine bir göz atın::"
```suggestion
msgstr ""
"Çok satırlı bir yapıya girilirken devamlılık satırları gereklidir. Örnek "
"olarak, şu :keyword:'`if` deyimine bir göz atın::"
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"çıkabilirsiniz: ''quit()'''."
```suggestion
"Dosya sonu karakteri (:kbd:`Control-D` Unix üzerine, :kbd:`Control-Z`  "
"Windows üzerine) yazılması, yorumlayıcının sıfır sonucu vermesine neden "
"olur.  Bu işe yaramazsa, aşağıdaki komutu yazarak yorumlayıcıdan "
"çıkabilirsiniz: ``quit()``."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"satırdaki karakterleri kaldırmak için geri alabiliyorsunuz."
```suggestion
"Yorumlayıcının satır düzenleme özellikleri arasında etkileşimli düzenleme, "
"geçmiş değiştirme ve `GNU Readline <https://tiswww.case.edu/php/chet/"
"readline/rltop.html>`_ kitaplığını destekleyen sistemlerde kod tamamlama "
"bulunur. Komut satırı düzenlemenin desteklenip desteklenmediğini görmek için "
"belki de en hızlı denetim, elde ettiğiniz ilk Python istemine :kbd:`Control-"
"P` yazmaktır.  Bip sesi çıkarsa komut satırı düzenlemeniz vardır; Tuşların "
"tanıtımı için :ref:`tut-interacting`. Hiçbir şey görünmüyorsa veya ``^P`` "
"yankılanıyorsa, komut satırı düzenlemesi kullanılamaz; yalnızca geçerli "
"satırdaki karakterleri kaldırmak için geri alabiliyorsunuz."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"tek tırnak ile alıntılanması önerilir."
```suggestion
msgstr ""
"Yorumlayıcıyı başlatmanın ikinci bir yolu, kabuğun :option:`-c` seçeneğine "
"benzer şekilde *komut* içindeki ifadeleri yürüten ``python -c komutu "
"[arg] ...`` dır. Python deyimleri genellikle boşluklar veya diğer "
"karakterler içerdiğinden kabukta özeldir, genellikle *komut* 'un tamamının "
"tek tırnak ile alıntılanması önerilir."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"bildirimini belirten bir karşılama iletisi yazdırır:"
```suggestion
msgstr ""
"Komutlar bir tty'den okunduğunda, yorumlayıcının *etkileşimli modda* olduğu "
"söylenir.  Bu modda, genellikle üç büyük işaret olan *öncelikli bilgi "
"sistemi* ile bir sonraki komutu ister (``>>>``); devam satırları için "
"*ikincil istem* ile sorar, varsayılan olarak üç nokta (``...``). "
"Yorumlayıcı, ilk istemi yazdırmadan önce sürüm numarasını ve telif hakkı "
"bildirimini belirten bir karşılama iletisi yazdırır:"
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"module [arg] ...'' kullanılarak çağrılabilir."
```suggestion
msgstr ""
"Bazı Python modülleri komut dosyası olarak da yararlıdır.  Bunlar, eğer tam "
"adını komut satırına yazarsanız *modül* için kaynak dosyası ``python -m "
"module [arg] ...`` kullanılarak çağrılabilir."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"önce :option:'-i' geçirilerek yapılabilir."
```suggestion
msgstr ""
"Bir komut dosyası kullanıldığında, bazen komut dosyasını çalıştırabilmek ve "
"daha sonra etkileşimli moda girebilmek yararlıdır.  Bu komut dosyasından "
"önce :option:`-i` geçirilerek yapılabilir."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"Tüm komut satırı seçenekleri :ref:'using-on-general' bölümünde açıklanmıştır."
```suggestion
msgstr ""
"Tüm komut satırı seçenekleri :ref:`using-on-general` bölümünde açıklanmıştır."
```

2022-03-13 15:46 UTC, irfan-karabacak commented on tutorial/interpreter.po
> +"modülün işlemesi için ''sys.argv'' içinde bırakılır."
```suggestion
msgstr ""
"Yorumlayıcı tarafından bilindiğinde, komut dosyası adı ve bundan sonraki ek "
"bağımsız değişkenler dizelerin listesine dönüştürülür ve ``sys`` modülündeki "
"``argv`` değişkenine atanır.  Bu listeye ``import sys`` öğesini yürüterek "
"erişebilirsiniz.  Listenin uzunluğu en az birdir; komut dosyası ve bağımsız "
"değişken verilmediğinde ``sys.argv[0]`` boş bir dizedir.  Komut dosyası adı "
"``'-'`` (standart giriş anlamına gelir) olarak verildiğinde, ``sys.argv[0]`` "
"``'-'`` olarak ayarlanır.  :option:`-c` *komut* kullanıldığında, ``sys."
"argv[0]`` `,`-c`` olarak ayarlanır.  :option:`-m` *modül* kullanıldığında, "
"``sys.argv[0]`` bulunan modülün tam adına ayarlanır.  Sonra bulunan "
"seçenekler :option:`-c` *komut* veya :option:`-m` *modül*, Python "
"yorumlayıcısının seçenek işlemesi tarafından tüketilmez, ancak komut veya "
"modülün işlemesi için ``sys.argv`` içinde bırakılır."
```

2022-04-02 12:42 UTC, egeakman requested changes

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +msgstr "Yorumlayıcı Çağırma"
```suggestion
msgstr "Yorumlayıcıyı Çağırma"
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"bin/python3.10` 'a yüklenir; Unix kabuğunuzun arama çubuğuna :file:`/usr/local/"
```suggestion
"bin/python3.10` 'a yüklenir; Unix kabuğunuzun arama yoluna (path) :file:`/usr/local/"
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"olduğundan, başka yerler de kullanım mümkündür; yerel Python gurunuza veya sistem "
```suggestion
"olduğundan, Python dizini başka bir yerde de olabilir; yerel Python gurunuza veya sistem "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"çıkabilirsiniz: ``quit()``."
```suggestion
"Dosya sonu karakteri (Unix'te :kbd:`Control-D`, Windows'ta :kbd:`Control-Z`) "
"yazılması, yorumlayıcının sıfır durumuyla (zero exit status) sonlanmasına neden "
"olur.  Bu işe yaramazsa, aşağıdaki komutu yazarak yorumlayıcıdan "
"çıkabilirsiniz: ``quit()``."
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"readline/rltop.html>`_ kitaplığını destekleyen sistemlerde kod tamamlama "
```suggestion
"readline/rltop.html>`_ kütüphanesini destekleyen sistemlerde kod tamamlama "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"tanıtımı için :ref:`tut-interacting`. Hiçbir şey görünmüyorsa veya ``^P`` "
```suggestion
"tanıtımı için :ref:`tut-interacting` 'e göz atabilirsiniz. Hiçbir şey görünmüyorsa veya ``^P`` "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"[arg] ...`` dır. Python deyimleri genellikle boşluklar veya diğer "
```suggestion
"benzer şekilde *komut* içindeki ifadeleri yürüten ``python -c *komut* "
"[argümanlar] ...`` 'dır. Python ifadelerigenellikle boşluklar veya diğer "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"module [arg] ...`` kullanılarak çağrılabilir."
```suggestion
"adını komut satırına yazarsanız *modül* için kaynak dosyası ``python -m "
"*modül* [argüman] ...`` kullanılarak çağrılabilir."
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"modülün işlemesi için ``sys.argv`` içinde bırakılır."
```suggestion
"Yorumlayıcı tarafından bilindiğinde, komut dosyası adı ve bundan sonraki ek "
"argüman dizelerin listesine dönüştürülür ve ``sys`` modülündeki "
"``argv`` değişkenine atanır.  Bu listeye ``import sys`` öğesini yürüterek "
"erişebilirsiniz.  Listenin uzunluğu en az birdir; komut dosyası ve argüman "
"verilmediğinde ``sys.argv[0]`` boş bir dizedir.  Komut dosyası adı "
"``'-'`` (standart giriş anlamına gelir) olarak verildiğinde, ``sys.argv[0]`` "
"``'-'`` olarak ayarlanır.  :option:`-c` *komut* kullanıldığında, ``sys."
"argv[0]``, ``-c`` olarak ayarlanır.  :option:`-m` *modül* kullanıldığında, "
"``sys.argv[0]`` bulunan modülün tam adına ayarlanır. "
":option:`-c` *komut* veya :option:`-m` *modül* 'den sonra bulunan seçenekler, Python "
"yorumlayıcısının seçenek işlemesi tarafından tüketilmez, ancak komut veya "
"modülün işlemesi için ``sys.argv`` içinde bırakılır."
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"sistemi* ile bir sonraki komutu ister (``>>>``); devam satırları için "
```suggestion
"söylenir.  Bu modda, genellikle üç büyük işaret olan *öncelikli bilgi "
"istemi* ile bir sonraki komutu ister (``>>>``); devam satırları için "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"olarak, şu :keyword:'`if` deyimine bir göz atın::"
```suggestion
"olarak, :keyword:'`if` ifadesine bir göz atın::"
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +msgstr "Etkileşimli mod hakkında daha fazla şey için bkz. :ref:`tut-interac`."
```suggestion
msgstr "Etkileşimli mod hakkında daha fazlası için bkz. :ref:`tut-interac`."
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +msgstr "Kaynak Kodu Kodlaması"
```suggestion
msgstr "Kaynak Kodu Şeması"
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"standart kitaplık tanımlayıcılar için yalnızca ASCII karakterleri kullansa "
```suggestion
"standart kütüphane tanımlayıcılar için yalnızca ASCII karakterleri kullansa "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"Varsayılan kod dışında bir kodlama bildirmek için, dosyanın *ilk* satırı "
```suggestion
"Varsayılan dil şeması dışında bir şema bildirmek için, dosyanın *ilk* satırı "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"Örneğin, Windows-1252 kodlamasının kullanılacağını bildirmek için, kaynak "
```suggestion
"Örneğin, Windows-1252 şemasının kullanılacağını bildirmek için, kaynak "
```

2022-04-02 12:42 UTC, egeakman commented on tutorial/interpreter.po
> +"dosyanın ikinci satırı olarak eklenmelidir.  Mesela::"
```suggestion
"*İlk satır* kuralının bir istisnası, kaynak kodun :ref:`UNIX \"shebang\" "
"line <tut-scripts>` satırı ile başlamasıdır.  Bu durumda, şema bildirimi "
"dosyanın ikinci satırı olarak eklenmelidir.  Örneğin::"
```

2022-04-02 12:54 UTC, egeakman approved these changes

2022-04-02 12:54 UTC, merged