Add files via upload
python-docs-tr/python-docs-tr pull request #27
Opened 2022-02-27 17:53 UTC by cvrnk

2022-02-27 18:11 UTC, egeakman requested changes

2022-02-27 18:11 UTC, egeakman commented on introduction.po
> +"kesirli kısmı olanlar (örneğin \"5,0\", \"1,6\" `)  :class:`float` türüne "
```suggestion
"Tam sayıların (örneğin ``2``, ``4``, ``20``) türü :class:`int` olup, "
"kesirli kısmı olanlar (örneğin ``5.0``, ``1.6``)  :class:`float` türüne "
```

2022-02-27 18:11 UTC, egeakman commented on introduction.po
> +"(ör. ```3+5j``)."
```suggestion
"(ör. ``3+5j``)."
```

2022-04-03 18:21 UTC, irfan-karabacak approved these changes
Bazı yerlerde :ref:`shallow copy <shallow_vs_deep_copy>` gibi yerlerin içindeki ifadeyi türkçe yapmışız ama bazılarında öyle değil o yüzden garantiye almak için onu düzeltim. Çok syntax hatası yok. Cümleler de mantıklı.

2022-04-03 18:21 UTC, irfan-karabacak commented on tutorial/introduction.po
> +msgstr ":ref:`formatdizileri`"
```suggestion
msgstr ":ref:`formatstrings`"
```

2022-04-03 18:21 UTC, irfan-karabacak commented on tutorial/introduction.po
> +msgstr ":ref:`eski-dize-biçimlendirme'"
```suggestion
msgstr ":ref:`old-string-formatting'"
```

2022-04-03 18:21 UTC, irfan-karabacak commented on tutorial/introduction.po
> +"alınabilir ve dilimlenebilir::"
```suggestion
"Dizeler gibi (ve diğer tüm yerleşik :term:`sequence' türleri), listeler dizine "
"alınabilir ve dilimlenebilir::"
```

2022-04-03 18:21 UTC, irfan-karabacak commented on tutorial/introduction.po
> +"döndürdüğü anlamına gelir::"
```suggestion
"Tüm dilim işlemleri, istenen ögeleri içeren yeni bir liste döndürür. Bu, "
"aşağıdaki dilimin listenin bir :ref:`shallow copy <shallow_vs_deep_copy>` "
"döndürdüğü anlamına gelir::"
```

2022-04-03 18:21 UTC, irfan-karabacak commented on tutorial/introduction.po
> +"Fibonacci_number>`_ ilk alt dizisini aşağıdaki gibi yazabiliriz:"
```suggestion
"Elbette Python'ı iki ile ikiyi toplamaktan daha komplike görevler için "
"kullanabiliriz. Örneğin, `Fibonacci series <https://en.wikipedia.org/wiki/"
"Fibonacci_number>`_ ilk alt dizisini aşağıdaki gibi yazabiliriz:"
```

2022-04-03 19:11 UTC, egeakman commented
> Bazı yerlerde :ref:`shallow copy <shallow_vs_deep_copy>` gibi yerlerin içindeki ifadeyi türkçe yapmışız ama bazılarında öyle değil o yüzden garantiye almak için onu düzeltim. Çok syntax hatası yok. Cümleler de mantıklı.

:sth:\`something <real_link>\` gibi olan yerlerde angle bracketların arasındaki `real_link` 'e dokunmamak şartıyla `something` yazan kısmı değiştirebiliriz. Hatta direkt Türkçesini yazmak istediğimiz başka yerler olursa şu şekilde: ``:meth:`yuvarlama <round>` `` gibi kullanabiliriz. Ama bence tersi gerekmedikçe orijinalini kullanmak daha iyi oluyor. @irfan-karabacak

2022-04-03 19:17 UTC, egeakman commented on tutorial/introduction.po
> +"Döngünün *gövdesi * girintilidir*: girinti, Python'un ifadeleri gruplama "
```suggestion
"Döngünün *gövdesi* *girintilidir* : girinti, Python'un ifadeleri gruplama "
```

2022-04-03 19:19 UTC, Ardasak commented
> > Bazı yerlerde :ref:`shallow copy <shallow_vs_deep_copy>` gibi yerlerin içindeki ifadeyi türkçe yapmışız ama bazılarında öyle değil o yüzden garantiye almak için onu düzeltim. Çok syntax hatası yok. Cümleler de mantıklı.
> 
> `` :sth:`something <real_link>` ``   gibi olan yerlerde angle bracketların arasındaki `real_link` 'e dokunmamak şartıyla `something` yazan kısmı değiştirebiliriz. Hatta direkt Türkçesini yazmak istediğimiz başka yerler olursa şu şekilde: `` :meth:`yuvarlama <round>` `` kullanabiliriz. Ama bence tersi gerekmedikçe orijinalini kullanmak daha iyi oluyor. @irfan-karabacak

ben bilmem kardeşim ben onları ingilizce yazıyom

2022-04-03 20:22 UTC, irfan-karabacak commented on tutorial/introduction.po
> +"kullanabilirsiniz:"
```suggestion
"``\\`` ile başlayan karakterlerin özel karakterler olarak yorumlanmasını "
"istemiyorsanız, ilk alıntıdan önce bir ``r`` ekleyerek *ham dizeleri* "
"kullanabilirsiniz:"
```

2022-04-08 22:10 UTC, egeakman requested changes

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"değil. Bir dize değişmezi içindeki bir karma karakter, yalnızca bir karma "
```suggestion
"veya kodun ardından bir yorum görünebilir, ancak bir dize sabiti içinde "
"değil. Bir dize sabiti içindeki bir hash karakteri, yalnızca bir hash "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"kısmı olanlar (örneğin ``5.0``, ``1.6``)  :class:`float` türüne sahiptir. "
```suggestion
"kısmı olanlar (örneğin ``5.0``, ``1.6``) :class:`float` türüne sahiptir.  "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"Bölme (``/``) her zaman bir ondalıklı sayı döndürür. :term:`floor partition` "
```suggestion
"Bölme (``/``) her zaman bir ondalıklı sayı döndürür. :term:`floor division` "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"maskeleyen aynı ada sahip bağımsız bir yerel değişken yaratırsınız."
```suggestion
"ona bir değer atamayın --- sihirli davranışları olan bu gömülü değişkeni "
"maskeleyen aynı ada sahip bağımsız bir yerel değişken yaratırsınız."
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"(ör. ``3+5j``)."
```suggestion
":class:`int` ve :class:`float` 'a ek olarak Python, :class:`~decimal.Decimal` "
"ve :class:`~fractions.Fraction` gibi diğer sayı türlerini de destekler. "
"Python ayrıca :ref:`karmaşık sayılar <typesnumeric>` için gömülü desteğe "
"sahiptir ve hayali kısmı belirtmek için ``j`` veya ``J`` son ekini kullanır "
"(ör. ``3+5j``)."
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"alınabilirler ve aynı sonuç [#]_ olur. ``\\`` tırnaklardan kaçmak için "
```suggestion
"alınabilirler ve aynı sonuç olur [#]_. ``\\`` tırnaklardan kaçmak için "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"kullanılabilir:"
```suggestion
"kullanılabilir::"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"işlevi, ekteki tırnak işaretlerini atlayarak ve çıkış karakterlerini ve özel "
```suggestion
"fonksiyonu, ekteki tırnak işaretlerini atlayarak ve çıkış karakterlerini ve özel "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"kullanabilirsiniz:"
```suggestion
"``\\`` ile başlayan karakterlerin özel karakterler olarak yorumlanmasını "
"istemiyorsanız, ilk alıntıdan önce bir ``r`` ekleyerek *ham dizeleri (raw strings)* "
"kullanabilirsiniz::"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"Dize değişmezleri birden çok satıra yayılabilir. Bunun bir yolu üçlü tırnak "
```suggestion
"Dize sabitleri birden çok satıra yayılabilir. Bunun bir yolu üçlü tırnak "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"\"*\" ile tekrarlanabilir:"
```suggestion
"Dizeler ``+`` operatörüyle birleştirilebilir (birbirine yapıştırılabilir) ve "
"``*`` ile tekrarlanabilir::"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"Yan yana iki veya daha fazla *dize değişmezi* (yani, tırnak işaretleri "
```suggestion
"Yan yana iki veya daha fazla *dize sabiti* (yani, tırnak işaretleri "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"Bu, değişkenler veya ifadelerle değil, yalnızca iki değişmez değerle "
```suggestion
"Bu, değişkenler veya ifadelerle değil, yalnızca iki sabit değerle "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"``+`` kullanın:"
```suggestion
"Değişkenleri veya bir değişkeni ve bir sabiti birleştirmek istiyorsanız, "
"``+`` kullanın:"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"bir dizedir::"
```suggestion
"olabilir). Karakterler için ayrı bir tür yoktur; karakterler yalnızca *bir* uzunluğunda "
"dizelerdir::"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"dikkat edin. Bu, ```s[:i] + s[i:]`` değerinin her zaman ``s`` değerine eşit "
```suggestion
"dikkat edin. Bu, ``s[:i] + s[i:]`` değerinin her zaman ``s`` değerine eşit "
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"vardır. n*, örneğin::"
```suggestion
"Ardından, *n* karakterli bir dizenin son karakterinin sağ kenarında *n* dizini "
"vardır, örneğin::"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +"uzunluğu indekslerin farkıdır. Örneğin, \"kelime[1:3]\"'nin uzunluğu 2'dir."
```suggestion
"uzunluğu indekslerin farkıdır. Örneğin, ``kelime[1:3]`` 'ün uzunluğu 2'dir."
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +msgstr ":ref:`metin sırası`"
```suggestion
msgstr ":ref:`textseq`"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +msgstr ":ref:`dize-yöntemleri`"
```suggestion
msgstr ":ref:`dize-yöntemleri <string-methods>`"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +msgstr ":ref:`f-dizeleri'"
```suggestion
msgstr ":ref:`f-strings`"
```

2022-04-08 22:10 UTC, egeakman commented on tutorial/introduction.po
> +msgstr "Gömülü ifadelere sahip dize değişmezleri."
```suggestion
msgstr "Gömülü ifadelere sahip dize sabitleri."
```

2022-04-11 16:22 UTC, egeakman approved these changes

2022-04-11 16:23 UTC, merged