Extending/embedding
python-docs-tr/python-docs-tr pull request #28
Opened 2022-03-02 22:19 UTC by irfan-karabacak

Bazı yerlerde syntax hataları olabilir.

2022-03-03 06:08 UTC, egeakman commented
Dosyaları silmemize gerek yok eğer ismi yanlış değil ise, sonra dosya olmadığı için conflict oluyor @Ardasak

2022-03-03 06:52 UTC, egeakman requested changes

2022-03-03 06:52 UTC, egeakman commented on extending/embedding.po
> +"Language-Team: TURKISH TEAM\n"
```suggestion
"Language-Team: TURKISH <python.docs.tr@gmail.com>\n"
```

2022-03-03 06:52 UTC, egeakman commented on extending/embedding.po
> +"Çevirilen değerleri kullanarak bir C rutinine bir fonksiyon çağrısı yapın, ve"
```suggestion
"Çevrilen değerleri kullanarak bir C rutinine bir fonksiyon çağrısı yapın, ve"
```
tdk

2022-03-03 06:52 UTC, egeakman commented on extending/embedding.po
> +"Çevirilen değerleri kullanarak bir Python arabirim rutinine bir fonksiyon "
```suggestion
"Çevrilen değerleri kullanarak bir Python arabirim rutinine bir fonksiyon "
```

2022-03-03 06:52 UTC, egeakman commented on extending/embedding.po
> +"ele alınmasının anlaşıldığı varsayılmaktadır. Bu hususlar, tercümanın "
```suggestion
"ele alınmasının anlaşıldığı varsayılmaktadır. Bu hususlar, yorumlayıcının "
```

2022-03-03 06:52 UTC, egeakman commented on extending/embedding.po
> +msgstr "Çok Üst Düzey Gömme"
```suggestion
msgstr "Saf Gömme"
```

2022-03-03 06:52 UTC, egeakman commented on extending/embedding.po
> +"dizisinin diğer değerleridir. Bu programı :ref:` derler, <compiling>` "
```suggestion
"dizisinin diğer değerleridir. Bu programı :ref:`derler, <compiling>`  ve "
```

2022-03-03 06:52 UTC, egeakman commented on extending/embedding.po
> +"olabilir). ). Bu komut dosyası, size doğrudan yardımcı olacak birkaç "
```suggestion
"olabilir). Bu komut dosyası, size doğrudan yardımcı olacak birkaç "
```

2022-03-13 17:17 UTC, Ardasak submitted a review, later dismissed

2022-03-13 17:33 UTC, egeakman approved these changes

2022-04-02 14:04 UTC, merged