License.po
python-docs-tr/python-docs-tr pull request #33
Opened 2022-04-10 15:36 UTC by irfan-karabacak

license.po bitti

2022-04-10 15:53 UTC, Ardasak requested changes
nice

2022-04-10 15:53 UTC, Ardasak commented on license.po
> +"devamı olarak oluşturuldu. Guido, diğerlerinden birçok katkı içermesine "
```suggestion
"devamı olarak oluşturuldu. Guido, diğerlerinin oldukça katkısı olmasına rağmen "
```

2022-04-10 15:53 UTC, Ardasak commented on license.po
> +msgstr "Yayın İzni"
```suggestion
msgstr "Yayın"
```

2022-04-10 15:53 UTC, Ardasak commented on license.po
> +msgstr "Türemiş Biçim"
```suggestion
msgstr "Şundan türedi:"
```

2022-04-10 15:53 UTC, Ardasak commented on license.po
> +msgstr "Yürütme izleme"
```suggestion
msgstr "Çalıştırma izleme"
```

2022-04-10 15:53 UTC, Ardasak commented on license.po
buraya bakılabilir şimdi telden review ediyom aklıma bişi gelmedi

2022-04-11 15:45 UTC, irfan-karabacak commented on license.po
> +msgstr "Yayın İzni"
Birazcık yayın izni anlamıyla kullanılmış gibiydi ama bence de böyle kalsın

2022-04-15 18:36 UTC, Ardasak commented on license.po
@egeakman sen çözersin burayı

2022-04-21 18:41 UTC, egeakman commented on license.po
> +"Marek Majkowski'nin uygulamasını içerir. Aşağıdaki notu içerir:"
```suggestion
":file:`Python/pyhash.c` dosyası, Dan Bernstein'ın SipHash24 algoritmasının "
"Marek Majkowski uygulamasını içerir. Burada aşağıdaki not yer alır::"
```

2022-04-24 15:18 UTC, egeakman requested changes

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"Python yazılımı ve belgeleri :ref:`PSF License Agreement <PSF-license>` "
```suggestion
"Python yazılımı ve belgeleri :ref:`PSF Lisans Anlaşması <PSF-license>` "
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"kelimesi kelimesine yorumlar aşağıdadır:"
```suggestion
"kelimesi kelimesine yorumlar aşağıdadır::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +msgstr ":mod:`trace` modülü aşağıdaki uyarıyı içerir:"
```suggestion
msgstr ":mod:`trace` modülü aşağıdaki uyarıyı içerir::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +msgstr ":mod:`xmlrpc.client` modülü aşağıdaki uyarıyı içerir:"
```suggestion
msgstr ":mod:`xmlrpc.client` modülü aşağıdaki uyarıyı içerir::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +msgstr ":mod:`select` modülü, kqueue arayüzü için aşağıdaki uyarıyı içerir:"
```suggestion
msgstr ":mod:`select` modülü, kqueue arayüzü için aşağıdaki uyarıyı içerir::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"aşağıdaki telif hakkı ve lisans bildirimini içerir:"
```suggestion
"C double'larının dizgilere ve dizgelerden dönüştürülmesi için dtoa ve strtod "
"C işlevlerini sağlayan :file:`Python/dtoa.c` dosyası, şu anda http://www.netlib.org/fp/ "
"adresinden erişilebilen David M. Gay'in aynı adlı dosyasından türetilmiştir. 16 Mart "
"2009'da alınan orijinal dosya, aşağıdaki telif hakkı ve lisans bildirimini içerir::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"kitaplıklarının bir kopyasını içerebilir, bu nedenle buraya OpenSSL "
```suggestion
"sistemi tarafından sağlanmışsa ek performans için OpenSSL kütüphanesini "
"kullanır. Ek olarak, Python için Windows ve macOS yükleyicileri, OpenSSL "
"kütüphanelerinin bir kopyasını içerebilir, bu nedenle buraya OpenSSL "
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"kullanılarak oluşturulmuştur:"
```suggestion
"kullanılarak oluşturulur::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"lisansının bir kopyasını ekliyoruz:"
```suggestion
"lisansının bir kopyasını ekliyoruz::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"kullanılarak oluşturulur:"
```suggestion
"kullanılarak oluşturulur::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"kullanılarak oluşturulur:"
```suggestion
"kullanılarak oluşturulur::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"-c14n2-testcases/ ve 3 maddeli BSD lisansı altında dağıtılır::"
```suggestion
":mod:`test` paketindeki C14N 2.0 test paketi (``Lib/test/xmltestdata/c14n-20/``), "
"https://www.w3.org/TR/xml-c14n2-testcases/ adresindeki W3C web sitesinden "
"alınmıştır ve 3 maddeli BSD lisansı altında dağıtılmaktadır::"
```

2022-04-24 15:18 UTC, egeakman commented on license.po
> +"Language-Team: TURKISH TEAM\n"
```suggestion
"Language-Team: TURKISH <python.docs.tr@gmail.com>\n"
```

2022-04-24 15:19 UTC, egeakman approved these changes

2022-04-24 15:21 UTC, Ardasak approved these changes

2022-04-24 15:21 UTC, merged