Add files via upload
python-docs-tr/python-docs-tr pull request #45
Opened 2022-06-16 22:24 UTC by MorphaxTheDeveloper

2022-06-17 22:39 UTC, MorphaxTheDeveloper commented
kabul etsene şunu ege

2022-06-18 16:23 UTC, Ardasak requested changes

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +"[x]``."
```suggestion
"Listenin sonuna bir öğe ekleyin. ``a[len(a):] = [x]`` ile"
"eşdeğerdir."
```

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +"insert(len(a), x)`` komutu ``a.append(x)`` komutu ile eşdeğerdir."
```suggestion
"Verilen pozisyona bir öğe ekleyin.  İlk argüman, daha önce ekleyeceğiniz "
"öğenin indeksidir, bu nedenle ``a.insert(0, x)`` listenin önüne ekler ve ``a."
"insert(len(a), x)`` komutu ``a.append(x)`` komutu ile eşdeğerdir."
```

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +msgstr "Listenin yüzeysel bir kopyasını döndürün.  Döndürmek için: ``a[:]``."
```suggestion
msgstr "Listenin yüzeysel bir kopyasını döndürün. ``a[:]`` ile eşdeğerdir."
```

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +"değerlendirilmesiyle elde edilen yeni bir liste olacaktır. Örneğin, bu "
```suggestion
"değerlendirilmesiyle elde edilen yeni bir liste olacaktır. Örneğin, "
```

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +"yinelenerek erişilir."
```suggestion
"term:`mutable` 'dır ve elemanları genellikle homojendir ve listenin üzerinde "
"yinelenerek erişilir."
```

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +"paketleme ve dizi açma'nın bir kombinasyonu olduğunu unutmayın."
```suggestion
"paketleme ve dizi açmanın bir kombinasyonu olduğunu unutmayın."
```

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +"Bazen bir listeyi üzerinde döngü yaparken değiştirmek cazip gelebilir; ancak "
```suggestion
"Bazen bir liste üzerinde döngü yaparken değiştirmek cazip gelebilir; ancak "
```

2022-06-18 16:23 UTC, Ardasak commented on tutorial/datastructures.po
> +"zincirlemesine izin veren mutasyona uğramış nesneyi döndürebilir."
```suggestion
"zincirlemesine izin veren değiştirilmiş nesneyi döndürebilir."
```

2022-06-18 16:41 UTC, Ardasak commented on tutorial/datastructures.po
> +"paketleme ve dizi açma'nın bir kombinasyonu olduğunu unutmayın."
```suggestion
"Buna uygun bir şekilde *dizi açma (sequence unpacking)* denir ve sağ taraftaki herhangi bir dizi "
"için çalışır.  Dizi açma, eşittir işaretinin sol tarafında dizideki eleman "
"sayısı kadar değişken olmasını gerektirir.  Çoklu atamanın aslında tuple "
"paketleme ve dizi açmanın bir kombinasyonu olduğunu unutmayın."
```

2022-06-18 16:44 UTC, egeakman requested changes

2022-06-18 16:44 UTC, egeakman commented on tutorial/datastructures.po
> +"Liste veri türünün bazı yöntemleri vardır.  Liste nesnelerinin tüm metodları "
```suggestion
"Liste veri türünün bazı yöntemleri daha vardır.  Liste nesnelerinin tüm metotları "
```

2022-06-19 13:32 UTC, egeakman approved these changes

2022-06-19 13:32 UTC, merged