faq/extending inital commit
python-docs-tr/python-docs-tr pull request #51
Opened 2022-07-01 11:39 UTC by MorphaxTheDeveloper

exxtra

2022-07-02 09:57 UTC, MorphaxTheDeveloper commented
egeeee

2022-07-14 17:28 UTC, sefikaozturk requested changes

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"belgesinde açıklanmıştır."
```suggestion
"dosyasında açıklanmıştır."
```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"koyun.  Kurucuları olan global veya statik C++ nesneleri muhtemelen iyi bir "
```suggestion
"Evet, C++'da bulunan C uyumluluk özelliklerini kullanarak.  ``extern \"C"
"\" { ... }`` komutunu Python include dosyalarının etrafına yerleştirin ve Python "
"yorumlayıcısı tarafından çağrılacak her fonksiyonun önüne ``extern \"C\"`` "
"koyun. Yapıcıları olan global veya statik C++ nesneleri muhtemelen iyi bir "
```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"koyun.  Kurucuları olan global veya statik C++ nesneleri muhtemelen iyi bir "
include dosyaları nasıl çevirmeli bilemedim. türkçe yazılım sitelerinde vs. direkt include şudur budur diye açıkladıkları için include olarak kalabilir ancak bir türkçeleştirme önerisi varsa değerlendirebiliriz. @irfan-karabacak

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"Cython ve Pyrex, Python'un C API'sini öğrenmek zorunda kalmadan bir uzantı "
```suggestion
"Cython ve Pyrex, Python'un C API'ını öğrenmek zorunda kalmadan bir uzantı "

```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +msgstr "C'den rastgele Python komutlarını nasıl çalıştırabilirim?"
```suggestion
msgstr "C'den rastgele Python komutlarını nasıl değerlendirebilirim?"

```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"Python bytes nesnelerinin null byte içerebileceğini unutmayın, bu nedenle "
```suggestion
"Python bayt nesnelerinin null bayt içerebileceğini unutmayın, bu nedenle "

```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"Ayrıca Python nesneleri için \"abstract\" arayüzü tarafından sağlanan üst "
```suggestion
"Ayrıca Python nesneleri için 'abstract' arayüzü tarafından sağlanan üst "

```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"siz sorumlusunuz."
```suggestion
"bir nesne için geçerlidir. Sonunda dönüş değerini ::c:func:`Py_DECREF`\\ 'lemekten "
"siz sorumlusunuz."
```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +msgstr "Aynı şeyi yapmak için özel bir nesne şöyle görünecektir:"
```suggestion
msgstr "Aynı şeyi yapan özel bir nesne şöyle görünecektir:"

```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"Setup dosyasını kullanarak bir modül ekledim ve make başarısız oldu; neden?"
```suggestion
"Kurulum dosyasını kullanarak bir modül ekledim ve derleme başarısız oldu; neden?"

```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"parçacığında çalıştırmanız gerekir ve :c:func:`PyRun_InteractiveLoop`un "
```suggestion
"Ancak bazen gömülü Python yorumlayıcısını geri kalan uygulamanızla aynı _thread_ (iş parçacığı) "
"içerisinde çalıştırmanız gerekir ve :c:func:`PyRun_InteractiveLoop`un "

```

2022-07-14 17:28 UTC, sefikaozturk commented on faq/extending.po
> +"parçacığında çalıştırmanız gerekir ve :c:func:`PyRun_InteractiveLoop`un "
sorun şu ki birçok türkçe kaynakta thread direkt thread olarak geçiyor ama iş parçacığı da bir çevirisi. göre insanlar anlasın diye ikisini de ekledim. 2. review'e göre değiştirebiliriz.

2022-07-15 11:42 UTC, irfan-karabacak commented on faq/extending.po
> +"parçacığında çalıştırmanız gerekir ve :c:func:`PyRun_InteractiveLoop`un "
stlid2.po'da da iş parçacığı olarak kullanmışız, anlaşılabilmesi açısından bence de belirtmek mantıklı

2022-07-15 11:45 UTC, irfan-karabacak commented on faq/extending.po
> +"koyun.  Kurucuları olan global veya statik C++ nesneleri muhtemelen iyi bir "
ben türkçesi için örnek bir kullanıma rastlamadım, review ettikten sonra da biraz bakacağım ama dediğin gibi include olarak da kalabilir

2022-07-15 11:45 UTC, irfan-karabacak submitted a review, later dismissed

2022-07-15 11:49 UTC, irfan-karabacak commented
ben şefikanın düzeltikleri dışında başka bir syntax ve anlam hatasıyla karşılaşmadım

2022-07-16 09:22 UTC, sefikaozturk approved these changes

2022-07-16 17:59 UTC, egeakman approved these changes

2022-07-16 17:59 UTC, merged