tutorial/classes
python-docs-tr/python-docs-tr pull request #8
Opened 2021-12-30 19:27 UTC by sefikaozturk

Halfway done, halfway to go!

Translated some of the terms as:
namespace - ad alanı
wrapper - aracı
scope - kapsam
semantics - semantik

2022-01-05 17:43 UTC, Ardasak submitted a review, later dismissed

2022-01-05 18:06 UTC, Ardasak commented
@egeakman ayıp oluyor.

2022-01-07 19:21 UTC, egeakman requested changes

2022-01-07 19:21 UTC, egeakman commented on tutorial/classes.po
> +"başlar.  Örneğin, ''x'' yukarıda oluşturulan :class:'MyClass' örneğiyse, "
```suggestion
"*abcde*, Smalltalk'taki \"örnek değişkenlerine\" ve C++'taki "
"\"veri üyelerine\" karşılık gelir.  Veri niteliklerinin önceden tanımlanması "
"gerekmez; yerel değişkenler gibi, ilk değer atandığı anda varlıkları "
"başlar.  Örneğin, ''x'' yukarıda oluşturulan :class:'MyClass' örneğiyse, "
```

2022-01-07 19:21 UTC, egeakman commented on tutorial/classes.po
> +"''MyClass.i'' fonksiyon olmadığından ''x.i'' değildir.  Ancak ''x.f', "
```suggestion
"fonksiyonlarını tanımlar.  Bu nedenle, örneğimizde ,'x.f'' geçerli bir "
"yöntem başvurusudur, ne de olsa ''MyClass.f'' bir fonksiyondur ancak "
"''MyClass.i'' metot olmadığından ''x.i'' değildir.  Ancak ''x.f', "
```

2022-01-18 10:12 UTC, egeakman commented
750. satırdan sonrası review edilecek

2022-02-04 01:05 UTC, egeakman requested changes
Doğru tırnak işaretinin kullanımına dikkat etmek gerekiyor.

Doğru işaretler:  ``  ve  `

Yanlış işaretler: '' ve '

@sefikaozturk 

@Ardasak 904. satırdan sonrası sende

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"standart sözdizimi olan ``obj.name`` kullanır.  Geçerli nitelik adları, "
```suggestion
"standart söz dizimi olan ``obj.name`` kullanır.  Geçerli nitelik adları, "
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"sınıfın yeni bir *örnek* öğesini oluşturur ve bu nesneyi ''x'' yerel "
```suggestion
"sınıfın yeni bir *örnek* öğesini oluşturur ve bu nesneyi ``x`` yerel "
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"nesneler oluşturmayı sever. Bu nedenle bir sınıf, :meth:'__init__' adlı özel "
```suggestion
"nesneler oluşturmayı sever. Bu nedenle bir sınıf, :meth:`__init__` adlı özel "
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"çağırır.  Bu örnekte, yeni başlatılmış bir örnek şu şekilde elde edilebilir:"
```suggestion
"Bir sınıf bir :meth:`__init__` metodunu tanımladığında, örnekleme işlemi "
"yeni oluşturulan sınıf örneği için otomatik olarak :meth:`__init__` öğesini "
"çağırır.  Bu örnekte, yeni başlatılmış bir örnek şu şekilde elde edilebilir:"
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"değişkenler :meth:'__init__'' için aktarılır.  Mesela::"
```suggestion
"Tabii ki, :meth:`__init__` yöntemi daha fazla esneklik için argümanlara "
"sahip olabilir.  Bu durumda, sınıf örnekleme işlecine verilen bağımsız "
"değişkenler :meth:`__init__` için aktarılır.  Mesela::"
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"başlar.  Örneğin, ''x'' yukarıda oluşturulan :class:'MyClass' örneğiyse, "
```suggestion
"başlar.  Örneğin, ``x`` yukarıda oluşturulan :class:`MyClass` örneğiyse, "
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"aşağıdaki kod parçası iz bırakmadan ''16'' değerini yazdırır::"
```suggestion
"aşağıdaki kod parçası iz bırakmadan ``16`` değerini yazdırır::"
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"*metot nesnesi*dir."
```suggestion
"fonksiyonlarını tanımlar.  Bu nedenle, örneğimizde, ``x.f`` geçerli bir "
"metot referansıdır, ne de olsa ``MyClass.f`` bir fonksiyondur ancak "
"``MyClass.i`` fonksiyon olmadığından ``x.i`` değildir.  Ancak ``x.f``, "
"``MyClass.f`` ile aynı şey değildir çünkü bir fonksiyon nesnesi değil, "
"*metot nesnesi* 'dir."
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +msgstr "Yöntem Nesneleri"
```suggestion
msgstr "Metot Nesneleri"
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +msgstr "Genellikle, bir yöntem bağlandıktan hemen sonra çağrılır::"
```suggestion
msgstr "Genellikle, bir metot bağlandıktan hemen sonra çağrılır::"
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"yani daha sonra depolanabilir ve çağrılabilir.  Mesela::"
```suggestion
":class:`MyClass` örneğinde, ``hello world`` string'ini döndürür. Lakin, "
"hemen bir metot çağırmak gerekli değildir: ``x.f`` bir metot nesnesidir, "
"yani daha sonra depolanabilir ve çağrılabilir.  Mesela::"
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"kullanılmasa bile- hata verir. "
```suggestion
"Bir yöntem çağrıldığında tam olarak ne gerçekleşir?  :meth:`f` fonksiyon "
"tanımı bir argüman belirtmiş olsa da, ``x.f()`` öğesinin yukarıda "
"bir argüman olmadan çağrıldığını fark etmiş olabilirsiniz.  Peki "
"argümana ne oldu? Elbette Python, argüman gerektiren bir "
"fonksiyon, argüman verilmemiş iken çağırılırsa --- "
"fonksiyon aslında kullanılmasa bile hata verir..."
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"bağımsız değişken listesiyle karşılık gelen fonksiyonu çağırmaya eşdeğerdir."
```suggestion
"Aslında, cevabı tahmin etmiş olabilirsiniz: yöntemlerle ilgili özel şey, "
"örnek nesnesinin fonksiyonun ilk argüman olarak geçirilmesidir.  "
"Örneğimizde, ``x.f()`` çağrısı tam olarak ``MyClass.f(x)`` ile eşdeğerdir.  "
"Genel olarak, *n* tane argümana sahip bir metodu çağırmak, ilk "
"argümandan önce metodun örnek nesnesi eklenerek oluşturulan bir "
"argüman listesiyle karşılık gelen fonksiyonu çağırmaya eşdeğerdir."
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"fonksiyon nesnesi bu yeni bağımsız değişken listesiyle çağrılır."
```suggestion
"argüman listesiyle çağrıldığında, örnek nesneden ve argüman "
"listesinden yeni bir argüman listesi oluşturulur ve "
"fonksiyon nesnesi bu yeni argüman listesiyle çağrılır."
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"sözlükler gibi :term:'mutable' nesnelerini içeren şaşırtıcı etkilere sahip "
```suggestion
":ref:`tut-object` 'te anlatıldığı gibi, paylaşılan veriler listeler ve "
"sözlükler gibi :term:`mutable` nesnelerini içeren şaşırtıcı etkilere sahip "
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"kullanım geleneğinden başka bir şey değildir, yani ''self'' adının Python "
```suggestion
"Genellikle, bir metodun ilk bağımsız değişkenine ``self`` denir.  Bu bir "
"kullanım geleneğinden başka bir şey değildir, yani ``self`` adının Python "
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"karıştırmaya yaradığını unutmayın."
```suggestion
"Buradaki ``f``, ``g`` ve ``h`` fonksiyonları nesnelerine başvuran :class:`C` "
"sınıfının bütün nitelikleridir ve sonuç olarak hepsi :class:`C` --- ``h`` "
"sınıfının örneklerinin metotları olarak tümüyle ``g`` 'ye eşdeğerdir.  Bu "
"kullanım şeklinin genellikle yalnızca bir programı okuyan kişinin kafasını "
"karıştırmaya yaradığını unutmayın."
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"Metotlar, ''self'' bağımsız değişkeninin metot niteliklerini kullanarak "
```suggestion
"Metotlar, ``self`` bağımsız değişkeninin metot niteliklerini kullanarak "
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"''object.__class__'' olarak depolanır."
```suggestion
"Her değer bir nesnedir ve bu nedenle bir *sınıf* (*type* olarak da adlandırılır) bulundurur. "
"``object.__class__`` olarak depolanır."
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +"tanımının sözdizimi şöyle görünür::"
```suggestion
"tanımının söz dizimi şöyle görünür::"
```

2022-02-04 01:05 UTC, egeakman commented on tutorial/classes.po
> +":class:'BaseClassName' adı, türetilmiş sınıf tanımını içeren bir kapsamda tanımlanmalıdır.  Temel "
```suggestion
":class:`BaseClassName` adı, türetilmiş sınıf tanımını içeren bir kapsamda tanımlanmalıdır.  Temel "
```

2022-02-04 17:30 UTC, Ardasak requested changes
adamsınnn

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"metot başvurusu geçerlidir."
```suggestion
"Türetilmiş sınıfların somutlaştırılmasında özel bir şey yoktur: ``DerivedClassName()`` sınıfın "
"yeni bir örneğini oluşturur.  Metot başvuruları aşağıdaki gibi çözümlenir: ilgili sınıf niteliği "
"aranır, gerekirse temel sınıflar zincirinin aşağısına inilir ve bu bir fonksiyon nesnesi veriyorsa "
"metot başvurusu geçerlidir."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"çağırabilir.  (C++ programcıları için: Python'daki tüm yöntemler etkili bir şekilde ''sanal''.)"
```suggestion
"Türetilmiş sınıflar, temel sınıflarının metotlarını geçersiz kılabilir.  Metotlar aynı nesnenin "
"diğer yöntemlerini çağırırken özel ayrıcalıkları olmadığından, aynı temel sınıfta tanımlanan başka "
"bir metodu çağıran bir temel sınıfın metodu, onu geçersiz kılan türetilmiş bir sınıfın metodunu "
"çağırabilir.  (C++ programcıları için: Python'daki tüm yöntemler etkili bir şekilde ``sanal``.)"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +msgstr "Python'un kalıtımla çalışan iki yerleşik işlevi vardır:"
```suggestion
msgstr "Python'un kalıtımla çalışan iki yerleşik fonksiyonu vardır:"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"çalıştığını unutmayın.)"
```suggestion
"Türetilmiş bir sınıfta geçersiz kılma yöntemi aslında yalnızca aynı adlı temel sınıf yöntemini "
"değiştirmek yerine genişletmek isteyebilir. Temel sınıf metodunu doğrudan çağırmanın basit bir yolu "
"vardır: sadece ``BaseClassName.methodname(self, arguments)`` çağırın.  Bu bazen müşteriler için de "
"yararlıdır.  (Bunun yalnızca temel sınıfa genel kapsamda ``BaseClassName`` olarak erişilebiliyorsa "
"çalıştığını unutmayın.)"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"olacaktır."
```suggestion
"Bir örneğin türünü denetlemek için :func:`isinstance` kullanın: ``isinstance(obj, int)`` yalnızca "
"``obj.__class__`` :class:`int` veya :class:`int` sınıfından türetilmiş bir sınıfsa ``True`` "
"olacaktır."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"olduğundan :class:'float' :class:'int' alt sınıfı değildir."
```suggestion
"Sınıf kalıtımını denetlemek için :func:`issubclass` kullanın: ``issubclass(bool, int)`` ``True`` 'dur, "
"çünkü :class:`bool` :class:`int` 'in bir alt sınıfıdır.  Ancak, ``issubclass(float, int)`` ``False`` "
"olduğundan :class:`float`, :class:`int` alt sınıfı değildir."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"şöyle görünür::"
```suggestion
"Python, çoklu kalıtım biçimini de destekler.  Birden çok temel sınıf içeren bir sınıf tanımı "
"şöyle görünür::"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"class:'Base1' temel sınıflarında aranır ve orada bulunamazsa: class:'Base2' vb."
```suggestion
"Basitçe, bir üst sınıftan devralınan nitelikleri aramayı, hiyerarşide çakışmanın olduğu aynı sınıfta "
"iki kez arama yapmadan, derinlik öncelikli, soldan sağa olarak düşünebilirsiniz. Bu nedenle, bir "
"nitelik :class:`DerivedClassName` içinde bulunamazsa, :class:`Base1` 'de, sonra (özyinelemeli olarak) :"
"class:`Base1` temel sınıflarında aranır ve orada bulunamazsa: class:`Base2` vb."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"daha güçlüdür."
```suggestion
"Aslında, durum bundan biraz daha karmaşıktır: yöntem çözümleme sırası, :func:`super` için işbirliği "
"çağrılarını desteklemek için dinamik olarak değişir.  Bu yaklaşım, diğer bazı çoklu kalıtım "
"dillerinde sonraki çağrı yöntemi olarak bilinir ve tekli kalıtım dillerinde bulunan süper çağrıdan "
"daha güçlüdür."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"releases/2.3/mro/ bakın."
```suggestion
"Çoklu kalıtımın tüm durumları bir veya daha fazla elmas ilişkisi gösterdiğinden (üst "
"sınıflardan en az birine, en alttaki sınıftan birden çok yol üzerinden erişilebildiği ilişkiler) "
"dinamik sıralama gereklidir.  Örneğin, tüm sınıflar :class:`object` öğesini devralır, bu nedenle "
"çoklu kalıtım durumu :class:'object'e ulaşmak için birden fazla yol sağlar.  Temel sınıflara "
"birden çok kez erişilmesini önlemek için, dinamik algoritma arama sırasını her sınıfta belirtilen "
"soldan sağa sıralamayı koruyacak şekilde doğrular, her üst öğeyi yalnızca bir kez çağırır ve "
"monotondur (yani bir sınıf, üst sınıfının öncelik sırasını etkilemeden alt sınıflandırılabilir). "
"Birlikte ele alındığında, bu özellikler çoklu kalıtım ile güvenilir ve genişletilebilir "
"sınıflar tasarlamayı mümkün kılır.  Daha fazla ayrıntı için https://www.python.org/download/"
"releases/2.3/mro/ bakın."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"veya veri üyesi olsun).  Bir uygulama detayıdır ve önceden haber verilmeksizin değiştirilebilir."
```suggestion
"Python'da bir nesnenin içinden erişilmesi dışında asla erişilemeyen \"özel\" örnek değişkenleri "
"yoktur.  Ancak, çoğu Python kodu tarafından izlenen bir kural vardır: alt çizgi (örneğin ``_spam``) ile "
"öneklenmiş bir ad API'nin genel olmayan bir parçası olarak kabul edilmelidir (bir fonksiyon, metot "
"veya veri üyesi olsun).  Bir uygulama detayıdır ve önceden haber verilmeksizin değiştirilebilir."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"bakılmaksızın yapılır."
```suggestion
"Sınıf-özel üyeler için geçerli bir kullanım örneği olduğundan (yani alt sınıflar tarafından "
"tanımlanan adlara sahip adların ad çakışmasını önlemek için), :dfn:`name mangling` adı verilen "
"böyle bir mekanizma için sınırlı destek vardır.  ``__spam`` formunun herhangi bir tanımlayıcısı (en "
"az iki satır altı, en fazla bir alt çizgi) metinsel olarak ``_classname__spam`` ile değiştirilir;  "
"Bu mangling, bir sınıfın tanımı içinde gerçekleştiği sürece tanımlayıcının sözdizimsel konumuna "
"bakılmaksızın yapılır."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"tanımlayıcısı tanıtsa bile çalışır."
```suggestion
"Yukarıdaki örnek, ``MappingSubclass`` sırasıyla ``Mapping`` sınıfında ``_Mapping__update`` ve "
"``mappingSubclass`` sınıfında ``_MappingSubclass__update`` ile değiştirildiği için ``__update`` "
"tanımlayıcısı tanıtsa bile çalışır."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"''delattr()'' ve doğrudan ''__dict__'' atıfta bulunurken de geçerlidir."
```suggestion
"``exec()`` veya ``eval()`` koduna geçirilen kodun çağırma sınıfının sınıf adını geçerli sınıf olarak "
"görmediğine dikkat edin; bu, etkisi aynı şekilde birlikte bayt derlenmiş kodla sınırlı olan "
"``global`` deyiminin etkisine benzer.  Aynı kısıtlama ``getattr()``, ``setattr()`` ve "
"``delattr()`` ve doğrudan ``__dict__`` atıfta bulunurken de geçerlidir."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"tanımlayabilirsiniz."
```suggestion
"Belirli bir soyut veri türünü bekleyen Python kodunun bir parçası genellikle bunun yerine bu veri "
"türünün yöntemlerine öykünen bir sınıfa geçirilebilir.  Örneğin, bir dosya nesnesinden bazı verileri "
"biçimlendiren bir fonksiyonunuz varsa, bunun yerine verileri bir dize arabelleğinden alan ve "
"bağımsız değişken olarak geçiren :meth:`read` ve :meth:`!readline` yöntemlerine sahip bir sınıf "
"tanımlayabilirsiniz."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"meth:'m', ve ''m.__func__'' yönteme karşılık gelen fonksiyon nesnesidir."
```suggestion
"Örnek yöntem nesnelerinin de nitelikleri vardır: ``m.__self__`` yöntemi olan örnek nesnedir :"
"meth:`m`, ve ``m.__func__`` yönteme karşılık gelen fonksiyon nesnesidir."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"döngüye alınabileceğini fark etmişsinizdir::"
```suggestion
"Şimdiye kadar büyük olasılıkla çoğu kapsayıcı nesnenin bir :keyword:`for` deyimi kullanılarak "
"döngüye alınabileceğini fark etmişsinizdir::"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"çağırabilirsiniz; Bu örnek, her şeyin nasıl çalıştığını gösterir::"
```suggestion
"Bu erişim tarzı açık, özlü ve kullanışlıdır.  Yineleyicilerin kullanımı Python'u istila eder ve "
"birleştirir.  Perde arkasında: keyword:`for` deyimi kapsayıcı nesne üzerinde :func:`iter` öğesini "
"çağırır.  Fonksiyon, kapsayıcıdaki öğelere teker teker erişen :meth:`~iterator.__next__` metodunu "
"tanımlayan bir yineleyici nesnesi döndürür.  Başka öğe olmadığında, :meth:`~iterator.__next__``, :"
"keyword:`!for` döngüsünün sonlandırılacağını bildiren bir :exc:`StopIteration` hatası "
"oluşturur.  :func:`next` yerleşik fonksiyonunu kullanarak :meth:`~iterator.__next__` yöntemini "
"çağırabilirsiniz; Bu örnek, her şeyin nasıl çalıştığını gösterir::"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"tanımlayın.  Sınıf  :meth:`__next__` tanımlarsa, :meth:`__iter__`  sadece  ``self`` döndürebilir::"
```suggestion
"Yineleme protokolünün arkasındaki mekaniği gördükten sonra, sınıflarınıza yineleme davranışı eklemek "
"kolaydır.  :meth:`~iterator.__next__` metodu ile bir nesne döndüren :meth:`__iter__` metodunu "
"tanımlayın.  Sınıf  :meth:`__next__` tanımlarsa, :meth:`__iter__`  sadece  ``self`` döndürebilir::"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"oluşturulmasının ne kadar da kolay olabileceğini gösterir::</generator>"
```suggestion
":term:`Üreteçler <generator>` yineleyiciler oluşturmak için basit ve güçlü bir araçtır.  Normal "
"fonksiyonlar gibi yazılırlar, ancak veri döndürmek istediklerinde :keyword:`yield` deyimini "
"kullanırlar.  Üzerinde her :func:`next` çağrıldığı zaman, üreteç kaldığı yerden devam eder (tüm veri "
"değerlerini ve hangi deyimin en son yürütüldüğını hatırlar).  Bu örnek, üreteçlerin "
"oluşturulmasının ne kadar da kolay olabileceğini gösterir::"
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"yöntemlerinin otomatik olarak oluşturulmasıdır."
```suggestion
"Üreteçlerle yapılabilecek her şey, önceki bölümde açıklandığı gibi sınıf tabanlı yineleyicilerle de "
"yapılabilir.  Üreteçleri bu kadar kompakt yapan şey: :meth:`__iter__` ve :meth:`~generator.__next__` "
"yöntemlerinin otomatik olarak oluşturulmasıdır."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"değişkenleri kullanmaya kıyasla çok daha net hale getirdi."
```suggestion
"Başka bir önemli özellik, yerel değişkenlerin ve yürütme durumunun çağrılar arasında otomatik olarak "
"kaydedilmesidir.  Bu, fonksiyonun yazılmasını kolaylaştırdı ve ``self.index`` ve ``self.data`` gibi "
"değişkenleri kullanmaya kıyasla çok daha net hale getirdi."
```

2022-02-04 17:30 UTC, Ardasak commented on tutorial/classes.po
> +"yazmaktan daha fazla çaba harcamadan yinelemeler oluşturmayı kolaylaştırır."
```suggestion
"Otomatik metot oluşturma ve kaydetme programı durumuna ek olarak, üreteçler sonlandırıldığında "
"otomatik olarak :exc:`StopIteration` 'ı yükseltirler. Birlikte, bu özellikler normal bir işlev "
"yazmaktan daha fazla çaba harcamadan yinelemeler oluşturmayı kolaylaştırır."
```

2022-02-04 17:32 UTC, Ardasak commented on tutorial/classes.po
> +"sahiptir."
```suggestion
"Sınıflar biraz yeni söz dizimi, üç yeni nesne türü ve bazı yeni semantiklere "
"sahiptir."
```

2022-02-04 17:32 UTC, Ardasak commented on tutorial/classes.po
> +msgstr "Sınıf Tanımlama Sözdizimi"
```suggestion
msgstr "Sınıf Tanımlama Söz dizimi"
```

2022-02-04 17:32 UTC, Ardasak commented on tutorial/classes.po
> +"eğilimindedir."
```suggestion
"Bazı basit üreteçler, listelere benzer bir söz dizimi kullanılarak ve köşeli ayraçlar yerine "
"parantezlerle kısaca kodlanabilir. Bu ifadeler, üreteçlerin kapsayıcı bir fonksiyon tarafından hemen "
"kullanıldığı durumlar için tasarlanmıştır.  Üreteç ifadeleri tam üreteç tanımlarından daha kompakt "
"ancak daha az çok yönlüdür ve aynı özellikle liste anlamalarından daha bellek dostu olma "
"eğilimindedir."
```

2022-02-04 19:52 UTC, sefikaozturk commented on tutorial/classes.po
> +msgstr "Genellikle, bir yöntem bağlandıktan hemen sonra çağrılır::"
Burada bir karışıklık olmuş galiba. Tekrar bakabilir misin?

2022-02-04 19:55 UTC, egeakman commented
Ne kadar çok argüman kelimesi geçmiş dökümantasyonda

2022-02-05 17:01 UTC, egeakman commented on tutorial/classes.po
> +msgstr "Genellikle, bir yöntem bağlandıktan hemen sonra çağrılır::"
Düzeltildi 👍

2022-02-05 17:10 UTC, egeakman commented on tutorial/classes.po
> +"Bu mangling, bir sınıfın tanımı içinde gerçekleştiği sürece tanımlayıcının sözdizimsel konumuna "
```suggestion
"Bu mangling, bir sınıfın tanımı içinde gerçekleştiği sürece tanımlayıcının söz dizimsel konumuna "
```

2022-02-05 17:13 UTC, egeakman approved these changes
Good to go

2022-02-08 13:49 UTC, Ardasak approved these changes

2022-02-08 13:50 UTC, merged