library/functions
python-docs-tr/python-docs-tr pull request #9
Opened 2021-12-30 22:49 UTC by Ardasak

Translated till 637th line.

2022-01-01 00:09 UTC, egeakman submitted a review, later dismissed

2022-07-10 20:41 UTC, Ardasak reviewed
reviewing my own work

2022-07-10 20:41 UTC, Ardasak commented on copyright.po
> +"Tam lisans ve izin bilgileri için :ref:`history-and-license` 'a göz atın."
```suggestion
"Bütün lisans ve izin bilgileri için :ref:`history-and-license` 'a göz atın."
```

2022-07-16 17:16 UTC, Ardasak reviewed
reviewing my own work, will continue from 800

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +msgstr "Not: :func:`iter` 'in aksine, :func:`aiter` 'in 2 argümanı yoktur."
```suggestion
msgstr "Not: :func:`iter` 'in aksine, :func:`aiter` 'in 2 argümanlı biçimi yoktur."
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"eşittir::"
```suggestion
"eşdeğerdir::"
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"``True`` ya da ``False`` değeri döndürür. *x* standart :ref:`truth testing "
```suggestion
"``True`` ya da ``False`` değeri döndürür. *x*, standart :ref:`truth testing "
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"değerini döndürür. :class:`bool`  sınıfı :class:`int` öğesinin bir alt "
```suggestion
"değerini döndürür. :class:`bool` sınıfı :class:`int` öğesinin bir alt "
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"string'i bayta çevirecektir."
```suggestion
"dizeyi bayta çevirecektir."
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +msgstr "Buna göre, yapıcı argümanlar :func:`bytearray` için yorumlanır."
```suggestion
msgstr "Buna göre, yapıcı argümanları :func:`bytearray` için yorumlanır."
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"Unicode kod noktası *i* tamsayısı olan bir karakteri temsil eden string "
```suggestion
"Unicode kod noktası *i* tamsayısı olan bir karakteri temsil eden dizeyi "
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"döndürür. Örneğin, ``chr(97)`` , ``'a'`` string'ini döndürürken, "
```suggestion
"döndürür. Örneğin, ``chr(97)`` , ``'a'`` dizesini döndürürken, "
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"``chr(8364)`` , ``'€'`` string'ini döndürür. Bu fonksiyon, :func:`ord` 'un "
```suggestion
"``chr(8364)`` , ``'€'`` dizesini döndürür. Bu fonksiyon, :func:`ord` 'un "
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"türeyen bir örneğin metodunun örneği aldığı gibi. Bu sınıf metodunu bu "
```suggestion
"türeyen bir örneğin metodunun örneği aldığı gibi. Bir sınıf metodunu bu "
```

2022-07-16 17:16 UTC, Ardasak commented on library/functions.po
> +"veya :func:`eval` fonksiyonları kullanılarak çalıştırılabilir."
```suggestion
"*source* 'ı bir koda veya AST nesnesine derler. Kod nesneleri :func:`exec` "
"veya :func:`eval` fonksiyonları kullanılarak çalıştırılabilir. "
"*source* normal bir dize, bayt dizesi veya bir AST nesnesi olabilir. "
"AST nesneleriyle nasıl çalışılacağını öğrenmek için :mod:`ast` modülüne bkz."
```

2022-07-16 17:39 UTC, Ardasak commented on library/functions.po
> +"ref:`gelecekteki özellikler <future>` 'a izin verileceğini kontrol eder. "
```suggestion
"ref:`gelecekteki özellikler <future>` 'e izin verileceğini kontrol eder. "
```

2022-07-16 17:39 UTC, Ardasak commented on library/functions.po
> +"gelecek ifadeleri *flags* argümanı tarafından belirtilirler, yine de "
```suggestion
"gelecek ifadeleri *flags* argümanı tarafından belirtilirler, her türlü"
```

2022-07-16 17:39 UTC, Ardasak commented on library/functions.po
> +"etrafında boşluk içermesine gerek yoktur. Örnek olarak, ``complex('1+2j')`` "
```suggestion
"etrafında boşluk içermemelidir. Örnek olarak, ``complex('1+2j')`` "
```

2022-07-16 17:39 UTC, Ardasak commented on library/functions.po
> +"olarak, ``delattr(x, 'foobar')`` , ``del x.foobar`` 'a eşittir."
```suggestion
"olarak, ``delattr(x, 'foobar')`` , ``del x.foobar`` 'a eşdeğerdir."
```

2022-11-05 17:46 UTC, egeakman requested changes

2022-11-05 17:46 UTC, egeakman commented on library/functions.po
> +"Language: tr_TR\n"
```suggestion
"Language: tr\n"
```

2022-11-05 17:52 UTC, egeakman approved these changes

2022-11-05 17:53 UTC, merged